2021-08-26 14:31:39,321    5684     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 14:31:39,323   16244     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:31:39,323   16244     INFO test_运营用户创建审批.py(23) - 初始化 Session
2021-08-26 14:31:40,011   16244     INFO test_运营用户创建审批.py(18) - 关闭 Session
2021-08-26 14:31:40,011   16244     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:31:40,026   16244     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:31:40,026   16244     INFO result.py(91) - 耗时： 0.7031576633453369
2021-08-26 14:31:40,027   16244     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:31:40,027   16244     INFO test_运营用户创建审批.py(197) - 初始化 Session
2021-08-26 14:31:40,324   16244     INFO test_运营用户创建审批.py(18) - 关闭 Session
2021-08-26 14:31:40,324   16244  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 221, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != '错误码:[MAS_01103],客户信息为空。'
- 操作成功
+ 错误码:[MAS_01103],客户信息为空。


2021-08-26 14:31:40,324   16244     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:31:40,324   16244     INFO result.py(91) - 耗时： 0.2972099781036377
2021-08-26 14:31:40,325    5684     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 14:31:40,325    5684    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 14:31:40,327    5684     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:01.266436
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-26 14:33:51,340   16344     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 14:33:51,342   14132     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:33:51,342   14132     INFO test_运营用户创建审批.py(23) - 初始化 Session
2021-08-26 14:33:51,985   14132     INFO test_运营用户创建审批.py(18) - 关闭 Session
2021-08-26 14:33:51,999   14132     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:33:51,999   14132     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:33:52,015   14132     INFO result.py(91) - 耗时： 0.6572399139404297
2021-08-26 14:33:52,015   14132     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:33:52,015   14132     INFO test_运营用户创建审批.py(197) - 初始化 Session
2021-08-26 14:33:52,313   14132     INFO test_运营用户创建审批.py(18) - 关闭 Session
2021-08-26 14:33:52,313   14132  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 221, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != '系统繁忙'
- 操作成功
+ 系统繁忙


2021-08-26 14:33:52,314   14132     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:33:52,314   14132     INFO result.py(91) - 耗时： 0.29743528366088867
2021-08-26 14:33:52,314   16344     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 14:33:52,314   16344    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 14:33:52,315   16344     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:01.251146
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-26 14:52:46,125   21572     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 14:52:46,126   11668     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:52:46,126   11668     INFO test_运营用户创建审批.py(23) - 初始化 Session
2021-08-26 14:52:46,572   11668     INFO test_运营用户创建审批.py(18) - 关闭 Session
2021-08-26 14:52:46,588   11668     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:52:46,588   11668     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:52:46,603   11668     INFO result.py(91) - 耗时： 0.4617950916290283
2021-08-26 14:52:46,603   11668     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:52:46,603   11668     INFO test_运营用户创建审批.py(197) - 初始化 Session
2021-08-26 14:52:46,723   11668     INFO test_运营用户创建审批.py(18) - 关闭 Session
2021-08-26 14:52:46,724   11668  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 222, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != '错误码:[MAS_01103],客户信息为空。'
- 操作成功
+ 错误码:[MAS_01103],客户信息为空。


2021-08-26 14:52:46,724   11668     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:52:46,724   11668     INFO result.py(91) - 耗时： 0.12102246284484863
2021-08-26 14:52:46,724   21572     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 14:52:46,724   21572    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 14:52:46,725   21572     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:00.805168
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-26 14:54:22,819   10028     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 14:54:22,822   19804     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:54:22,822   19804     INFO test_运营用户创建审批.py(23) - 初始化 Session
2021-08-26 14:54:23,214   19804     INFO test_运营用户创建审批.py(18) - 关闭 Session
2021-08-26 14:54:23,230   19804     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:54:23,230   19804     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:54:23,230   19804     INFO result.py(91) - 耗时： 0.4089057445526123
2021-08-26 14:54:23,245   19804     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:54:23,245   19804     INFO test_运营用户创建审批.py(197) - 初始化 Session
2021-08-26 14:54:23,336   19804     INFO test_运营用户创建审批.py(209) - applyId为,applyId
2021-08-26 14:54:23,365   19804     INFO test_运营用户创建审批.py(18) - 关闭 Session
2021-08-26 14:54:23,366   19804  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 222, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != '错误码:[MAS_01103],客户信息为空。'
- 操作成功
+ 错误码:[MAS_01103],客户信息为空。


2021-08-26 14:54:23,366   19804     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:54:23,366   19804     INFO result.py(91) - 耗时： 0.12095379829406738
2021-08-26 14:54:23,366   10028     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 14:54:23,366   10028    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 14:54:23,367   10028     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:00.739929
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-26 14:58:13,274   17744     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 14:58:13,275    1032     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:58:13,276    1032     INFO test_运营用户创建审批.py(23) - 初始化 Session
2021-08-26 14:58:13,780    1032     INFO test_运营用户创建审批.py(18) - 关闭 Session
2021-08-26 14:58:13,780    1032     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:58:13,780    1032     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:58:13,780    1032     INFO result.py(91) - 耗时： 0.5056798458099365
2021-08-26 14:58:13,796    1032     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:58:13,796    1032     INFO test_运营用户创建审批.py(197) - 初始化 Session
2021-08-26 14:58:13,887    1032     INFO test_运营用户创建审批.py(209) - 1147393
2021-08-26 14:58:13,919    1032     INFO test_运营用户创建审批.py(18) - 关闭 Session
2021-08-26 14:58:13,920    1032  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 222, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != '错误码:[MAS_01103],客户信息为空。'
- 操作成功
+ 错误码:[MAS_01103],客户信息为空。


2021-08-26 14:58:13,920    1032     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:58:13,920    1032     INFO result.py(91) - 耗时： 0.12369275093078613
2021-08-26 14:58:13,920   17744     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 14:58:13,920   17744    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 14:58:13,921   17744     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:00.853141
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-26 14:59:29,789   15412     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 14:59:29,791   10904     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:59:29,792   10904     INFO test_运营用户创建审批.py(23) - 初始化 Session
2021-08-26 14:59:30,231   10904     INFO test_运营用户创建审批.py(18) - 关闭 Session
2021-08-26 14:59:30,246   10904     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:59:30,246   10904     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:59:30,261   10904     INFO result.py(91) - 耗时： 0.45381712913513184
2021-08-26 14:59:30,261   10904     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:59:30,261   10904     INFO test_运营用户创建审批.py(197) - 初始化 Session
2021-08-26 14:59:30,386   10904     INFO test_运营用户创建审批.py(18) - 关闭 Session
2021-08-26 14:59:30,386   10904  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 223, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != '错误码:[MAS_01103],客户信息为空。'
- 操作成功
+ 错误码:[MAS_01103],客户信息为空。


2021-08-26 14:59:30,386   10904     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 14:59:30,386   10904     INFO result.py(91) - 耗时： 0.12458038330078125
2021-08-26 14:59:30,387   15412     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 14:59:30,387   15412    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 14:59:30,388   15412     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:00.801504
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-26 15:01:36,654   11368     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 15:01:36,655    3060     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 15:01:36,655    3060     INFO test_运营用户创建审批.py(23) - 初始化 Session
2021-08-26 15:01:37,166    3060     INFO test_运营用户创建审批.py(18) - 关闭 Session
2021-08-26 15:01:37,166    3060     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 15:01:37,182    3060     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 15:01:37,198    3060     INFO result.py(91) - 耗时： 0.5268902778625488
2021-08-26 15:01:37,198    3060     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 15:01:37,198    3060     INFO test_运营用户创建审批.py(197) - 初始化 Session
2021-08-26 15:01:37,271    3060     INFO test_运营用户创建审批.py(210) - applyId的植为'1147393'
2021-08-26 15:01:37,299    3060     INFO test_运营用户创建审批.py(18) - 关闭 Session
2021-08-26 15:01:37,300    3060  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 224, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != '错误码:[MAS_01103],客户信息为空。'
- 操作成功
+ 错误码:[MAS_01103],客户信息为空。


2021-08-26 15:01:37,300    3060     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 15:01:37,300    3060     INFO result.py(91) - 耗时： 0.10209989547729492
2021-08-26 15:01:37,300   11368     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 15:01:37,300   11368    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 15:01:37,301   11368     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:00.849912
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-26 18:43:19,323   18164     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 18:43:19,324   17532     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:43:19,378   17532     INFO test_运营用户创建审批.py(30) - 初始化 Session
2021-08-26 18:43:24,861   17532     INFO test_运营用户创建审批.py(24) - 关闭 Session
2021-08-26 18:43:24,861   17532     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:43:24,877   17532     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:43:24,877   17532     INFO result.py(91) - 耗时： 5.553205966949463
2021-08-26 18:43:24,892   17532     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:43:24,892   17532     INFO test_运营用户创建审批.py(207) - 获取手机号
2021-08-26 18:43:24,892   17532     INFO test_运营用户创建审批.py(24) - 关闭 Session
2021-08-26 18:43:24,893   17532    ERROR result.py(175) - 测试产生错误： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 208, in test_submitAudit提交审核
    cd_clnt_apply_info(phone)
  File "F:\python\EDDID_CDMS\Common\eddid_data_update.py", line 8, in cd_clnt_apply_info
    sql="update cd_clnt_wc_match set resolution_status='FALSE'  where wc_case_id IN(select id from cd_clnt_wc_case where check_id in(select id from  cd_clnt_check_info where apply_id in (select apply_id from cd_clnt_apply_basisinfo where apply_no in (SELECT apply_no applyno FROM cd_clnt_apply_basisinfo WHERE apply_id =(select apply_id from cd_clnt_apply_info where phone_no='{phone}')))))".format(
KeyError: 'phone'

2021-08-26 18:43:24,893   17532     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:43:24,893   17532     INFO result.py(91) - 耗时： 0.0009686946868896484
2021-08-26 18:43:24,893   18164     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 18:43:24,893   18164    ERROR test_runner.py(195) - 
Error	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 18:43:24,894   18164     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:05.776164
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：1

2021-08-26 18:44:11,210   18368     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 18:44:11,211    5524     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:44:11,212    5524     INFO test_运营用户创建审批.py(30) - 初始化 Session
2021-08-26 18:44:16,720    5524     INFO test_运营用户创建审批.py(24) - 关闭 Session
2021-08-26 18:44:16,720    5524     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:44:16,720    5524     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:44:16,720    5524     INFO result.py(91) - 耗时： 5.508285999298096
2021-08-26 18:44:16,735    5524     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:44:16,735    5524     INFO test_运营用户创建审批.py(207) - 获取手机号
2021-08-26 18:44:16,882    5524     INFO test_运营用户创建审批.py(209) - 已完成修改WorldCheck的状态为FALSE
2021-08-26 18:44:21,094    5524     INFO test_运营用户创建审批.py(24) - 关闭 Session
2021-08-26 18:44:21,094    5524    ERROR result.py(175) - 测试产生错误： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 220, in test_submitAudit提交审核
    applyId = cd_clnt_apply_info(phone)[0][0]
TypeError: 'NoneType' object is not subscriptable

2021-08-26 18:44:21,094    5524     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:44:21,094    5524     INFO result.py(91) - 耗时： 4.358972787857056
2021-08-26 18:44:21,094   18368     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 18:44:21,094   18368    ERROR test_runner.py(195) - 
Error	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 18:44:21,095   18368     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:10.098091
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：1

2021-08-26 18:46:08,644    9104     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 18:46:08,645   18540     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:46:08,668   18540     INFO test_运营用户创建审批.py(30) - 初始化 Session
2021-08-26 18:46:14,119   18540     INFO test_运营用户创建审批.py(24) - 关闭 Session
2021-08-26 18:46:14,134   18540     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:46:14,134   18540     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:46:14,149   18540     INFO result.py(91) - 耗时： 5.4873127937316895
2021-08-26 18:46:14,165   18540     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:46:14,165   18540     INFO test_运营用户创建审批.py(207) - 获取手机号
2021-08-26 18:46:14,314   18540     INFO test_运营用户创建审批.py(209) - 已完成修改WorldCheck的状态为FALSE
2021-08-26 18:46:18,510   18540     INFO test_运营用户创建审批.py(24) - 关闭 Session
2021-08-26 18:46:18,511   18540    ERROR result.py(175) - 测试产生错误： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 220, in test_submitAudit提交审核
    applyId = cd_clnt_apply_info(phone)[0][0]
TypeError: 'NoneType' object is not subscriptable

2021-08-26 18:46:18,511   18540     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:46:18,511   18540     INFO result.py(91) - 耗时： 4.3453991413116455
2021-08-26 18:46:18,511    9104     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 18:46:18,511    9104    ERROR test_runner.py(195) - 
Error	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 18:46:18,512    9104     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:10.069962
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：1

2021-08-26 18:53:55,948   20008     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 18:53:55,950   24984     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:53:56,012   24984     INFO test_运营用户创建审批.py(30) - 初始化 Session
2021-08-26 18:54:01,464   24984     INFO test_运营用户创建审批.py(24) - 关闭 Session
2021-08-26 18:54:01,479   24984     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:54:01,479   24984     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:54:01,479   24984     INFO result.py(91) - 耗时： 5.529270172119141
2021-08-26 18:54:01,494   24984     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:54:01,659   24984     INFO test_运营用户创建审批.py(209) - 已完成修改WorldCheck的状态为FALSE
2021-08-26 18:54:05,740   24984     INFO test_运营用户创建审批.py(220) - 提交审核获取到的手机号为：11808569618
2021-08-26 18:54:05,874   24984     INFO test_运营用户创建审批.py(223) - applyId的值为：None
2021-08-26 18:54:05,907   24984     INFO test_运营用户创建审批.py(24) - 关闭 Session
2021-08-26 18:54:05,908   24984  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 235, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != '错误码:[MAS_01103],客户信息为空。'
- 操作成功
+ 错误码:[MAS_01103],客户信息为空。


2021-08-26 18:54:05,908   24984     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 18:54:05,908   24984     INFO result.py(91) - 耗时： 4.413370847702026
2021-08-26 18:54:05,908   20008     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 18:54:05,908   20008    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 18:54:05,909   20008     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:10.222977
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-26 19:00:39,506   19872     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 19:00:39,508   13204     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:00:39,570   13204     INFO test_运营用户创建审批.py(32) - 初始化 Session
2021-08-26 19:00:39,725   13204     INFO test_运营用户创建审批.py(41) - 接口请求url为：
2021-08-26 19:00:44,983   13204     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:00:44,983   13204     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:00:44,998   13204     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:00:44,998   13204     INFO result.py(91) - 耗时： 5.490333795547485
2021-08-26 19:00:45,014   13204     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:00:45,193   13204     INFO test_运营用户创建审批.py(213) - 已完成修改WorldCheck的状态为FALSE
2021-08-26 19:00:49,229   13204     INFO test_运营用户创建审批.py(223) - 接口请求url为：
2021-08-26 19:00:49,229   13204     INFO test_运营用户创建审批.py(225) - 提交审核获取到的手机号为：10889536996
2021-08-26 19:00:49,363   13204     INFO test_运营用户创建审批.py(228) - 请求数据库cd_clnt_apply_info查询到applyId的值为：None
2021-08-26 19:00:49,429   13204     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:00:49,430   13204  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 240, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != '错误码：[CDMS_04008]，申请单编号为空。'
- 操作成功
+ 错误码：[CDMS_04008]，申请单编号为空。


2021-08-26 19:00:49,430   13204     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:00:49,430   13204     INFO result.py(91) - 耗时： 4.415864944458008
2021-08-26 19:00:49,430   19872     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:00:49,430   19872    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:00:49,431   19872     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:10.201155
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-26 19:05:27,026   21156     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 19:05:27,028   25660     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:05:27,029   25660     INFO test_运营用户创建审批.py(32) - 初始化 Session
2021-08-26 19:05:27,258   25660     INFO test_运营用户创建审批.py(41) - 接口请求url为：
2021-08-26 19:05:32,518   25660     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:05:32,549   25660     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:05:32,549   25660     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:05:32,549   25660     INFO result.py(91) - 耗时： 5.520256757736206
2021-08-26 19:05:32,565   25660     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:05:32,715   25660     INFO test_运营用户创建审批.py(213) - 已完成修改WorldCheck的状态为FALSE
2021-08-26 19:05:36,806   25660     INFO test_运营用户创建审批.py(223) - 接口请求url为：
2021-08-26 19:05:36,807   25660     INFO test_运营用户创建审批.py(225) - 提交审核获取到的手机号为：10209090034
2021-08-26 19:05:36,949   25660     INFO test_运营用户创建审批.py(228) - 请求数据库cd_clnt_apply_info查询到applyId的值为：None
2021-08-26 19:05:36,979   25660     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:05:36,980   25660  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 240, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != '错误码：[CDMS_04008]，申请单编号为空。'
- 操作成功
+ 错误码：[CDMS_04008]，申请单编号为空。


2021-08-26 19:05:36,980   25660     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:05:36,980   25660     INFO result.py(91) - 耗时： 4.415088176727295
2021-08-26 19:05:36,980   21156     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:05:36,980   21156    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:05:36,981   21156     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:10.150191
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-26 19:07:54,089   15632     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 19:07:54,090   20676     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:07:54,090   20676     INFO test_运营用户创建审批.py(32) - 初始化 Session
2021-08-26 19:07:54,297   20676     INFO test_运营用户创建审批.py(41) - 接口请求url为：
2021-08-26 19:07:59,567   20676     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:07:59,567   20676     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:07:59,567   20676     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:07:59,567   20676     INFO result.py(91) - 耗时： 5.476747989654541
2021-08-26 19:07:59,567   20676     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:07:59,712   20676     INFO test_运营用户创建审批.py(213) - 已完成修改WorldCheck的状态为FALSE
2021-08-26 19:08:03,752   20676     INFO test_运营用户创建审批.py(223) - 接口请求url为：
2021-08-26 19:08:03,752   20676     INFO test_运营用户创建审批.py(225) - 提交审核获取到的手机号为：19898077267
2021-08-26 19:08:03,825   20676     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:08:03,825   20676    ERROR result.py(175) - 测试产生错误： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 226, in test_submitAudit提交审核
    applyId = cd_clnt_apply_info(phone)
  File "F:\python\EDDID_CDMS\Common\eddid_data_select.py", line 9, in cd_clnt_apply_info
    applyid=apply_id[0][0]
IndexError: tuple index out of range

2021-08-26 19:08:03,826   20676     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:08:03,826   20676     INFO result.py(91) - 耗时： 4.258055210113525
2021-08-26 19:08:03,826   15632     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:08:03,826   15632    ERROR test_runner.py(195) - 
Error	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:08:03,827   15632     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:09.935320
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：1

2021-08-26 19:13:15,391   26276     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 19:13:15,393    8064     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:13:15,393    8064     INFO test_运营用户创建审批.py(32) - 初始化 Session
2021-08-26 19:13:15,600    8064     INFO test_运营用户创建审批.py(41) - 接口请求url为：
2021-08-26 19:13:20,919    8064     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:13:20,919    8064     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:13:20,919    8064     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:13:20,934    8064     INFO result.py(91) - 耗时： 5.525180816650391
2021-08-26 19:13:20,934    8064     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:13:21,111    8064     INFO test_运营用户创建审批.py(213) - 已完成修改WorldCheck的状态为FALSE
2021-08-26 19:13:25,149    8064     INFO test_运营用户创建审批.py(223) - 接口请求url为：
2021-08-26 19:13:25,150    8064     INFO test_运营用户创建审批.py(225) - 提交审核获取到的手机号为：16230228812
2021-08-26 19:13:25,213    8064     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:13:25,213    8064    ERROR result.py(175) - 测试产生错误： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 226, in test_submitAudit提交审核
    applyId = cd_clnt_apply_info(phone)
  File "F:\python\EDDID_CDMS\Common\eddid_data_select.py", line 6, in cd_clnt_apply_info
    apply_id = SQL_Check.eddid_gfss_sit(database="eddid_gfss_sit",
IndexError: tuple index out of range

2021-08-26 19:13:25,214    8064     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:13:25,214    8064     INFO result.py(91) - 耗时： 4.280611991882324
2021-08-26 19:13:25,214   26276     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:13:25,214   26276    ERROR test_runner.py(195) - 
Error	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:13:25,215   26276     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:10.014039
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：1

2021-08-26 19:15:56,900   22512     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 19:15:56,902   25080     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:15:56,903   25080     INFO test_运营用户创建审批.py(32) - 初始化 Session
2021-08-26 19:15:57,069   25080     INFO test_运营用户创建审批.py(41) - 接口请求url为：
2021-08-26 19:16:02,350   25080     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:16:02,366   25080     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:16:02,381   25080     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:16:02,397   25080     INFO result.py(91) - 耗时： 5.478368759155273
2021-08-26 19:16:02,414   25080     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:16:02,559   25080     INFO test_运营用户创建审批.py(213) - 已完成修改WorldCheck的状态为FALSE
2021-08-26 19:16:06,590   25080     INFO test_运营用户创建审批.py(223) - 接口请求url为：
2021-08-26 19:16:06,590   25080     INFO test_运营用户创建审批.py(225) - 提交审核获取到的手机号为：10959500602
2021-08-26 19:16:06,654   25080     INFO test_运营用户创建审批.py(228) - 请求数据库cd_clnt_apply_info查询到applyId的值为：()
2021-08-26 19:16:06,689   25080     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:16:06,690   25080  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 240, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != 'JSON invalid format'
- 操作成功
+ JSON invalid format


2021-08-26 19:16:06,690   25080     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:16:06,690   25080     INFO result.py(91) - 耗时： 4.276490211486816
2021-08-26 19:16:06,690   22512     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:16:06,690   22512    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:16:06,691   22512     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:09.994231
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-26 19:19:48,590    9132     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 19:19:48,592   11380     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:19:48,593   11380     INFO test_运营用户创建审批.py(32) - 初始化 Session
2021-08-26 19:19:48,818   11380     INFO test_运营用户创建审批.py(42) - 接口请求url为：
2021-08-26 19:19:54,098   11380     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:19:54,113   11380     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:19:54,113   11380     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:19:54,129   11380     INFO result.py(91) - 耗时： 5.521281719207764
2021-08-26 19:19:54,145   11380     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:19:54,324   11380     INFO test_运营用户创建审批.py(214) - 已完成修改WorldCheck的状态为FALSE
2021-08-26 19:19:58,366   11380     INFO test_运营用户创建审批.py(224) - 接口请求url为：
2021-08-26 19:19:58,367   11380     INFO test_运营用户创建审批.py(226) - 提交审核获取到的手机号为：12394306928
2021-08-26 19:19:58,427   11380     INFO test_运营用户创建审批.py(229) - 请求数据库cd_clnt_apply_info查询到applyId的值为：()
2021-08-26 19:19:58,461   11380     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:19:58,461   11380  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 241, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != 'JSON invalid format'
- 操作成功
+ JSON invalid format


2021-08-26 19:19:58,461   11380     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:19:58,462   11380     INFO result.py(91) - 耗时： 4.3161797523498535
2021-08-26 19:19:58,462    9132     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:19:58,462    9132    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:19:58,463    9132     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:10.075537
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-26 19:21:15,280   18196     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 19:21:15,282   14448     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:21:15,301   14448     INFO test_运营用户创建审批.py(32) - 初始化 Session
2021-08-26 19:21:15,518   14448     INFO test_运营用户创建审批.py(42) - 接口请求url为：
2021-08-26 19:21:20,786   14448     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:21:20,786   14448     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:21:20,802   14448     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:21:20,818   14448     INFO result.py(91) - 耗时： 5.501280784606934
2021-08-26 19:21:20,818   14448     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:21:20,971   14448     INFO test_运营用户创建审批.py(214) - 已完成修改WorldCheck的状态为FALSE
2021-08-26 19:21:25,036   14448     INFO test_运营用户创建审批.py(227) - 接口请求url为：
2021-08-26 19:21:25,036   14448     INFO test_运营用户创建审批.py(229) - 提交审核获取到的手机号为：19760274508
2021-08-26 19:21:25,099   14448     INFO test_运营用户创建审批.py(232) - 请求数据库cd_clnt_apply_info查询到applyId的值为：()
2021-08-26 19:21:25,131   14448     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:21:25,132   14448  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 244, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != 'JSON invalid format'
- 操作成功
+ JSON invalid format


2021-08-26 19:21:25,132   14448     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:21:25,132   14448     INFO result.py(91) - 耗时： 4.314119577407837
2021-08-26 19:21:25,132   18196     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:21:25,132   18196    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:21:25,133   18196     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:10.059543
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-26 19:22:53,342    2708     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 19:22:53,343   25552     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:22:53,344   25552     INFO test_运营用户创建审批.py(32) - 初始化 Session
2021-08-26 19:22:53,620   25552     INFO test_运营用户创建审批.py(42) - 接口请求url为：
2021-08-26 19:22:58,917   25552     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:22:58,917   25552     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:22:58,917   25552     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:22:58,932   25552     INFO result.py(91) - 耗时： 5.573084115982056
2021-08-26 19:22:58,947   25552     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:22:59,093   25552     INFO test_运营用户创建审批.py(214) - 已完成修改WorldCheck的状态为FALSE
2021-08-26 19:23:03,172   25552     INFO test_运营用户创建审批.py(227) - 接口请求url为：
2021-08-26 19:23:03,172   25552     INFO test_运营用户创建审批.py(229) - 提交审核获取到的手机号为：11249468368
2021-08-26 19:23:03,250   25552     INFO test_运营用户创建审批.py(232) - 请求数据库cd_clnt_apply_info查询到applyId的值为：()
2021-08-26 19:23:03,283   25552     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:23:03,284   25552  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 244, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != 'JSON invalid format'
- 操作成功
+ JSON invalid format


2021-08-26 19:23:03,284   25552     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:23:03,284   25552     INFO result.py(91) - 耗时： 4.336708307266235
2021-08-26 19:23:03,284    2708     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:23:03,285    2708    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:23:03,285    2708     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:10.150800
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-26 19:30:05,391    6160     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-26 19:30:05,393    7720     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:30:05,394    7720     INFO test_运营用户创建审批.py(32) - 初始化 Session
2021-08-26 19:30:05,656    7720     INFO test_运营用户创建审批.py(42) - 接口请求url为：
2021-08-26 19:30:10,961    7720     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:30:10,961    7720     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:30:10,961    7720     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:30:10,961    7720     INFO result.py(91) - 耗时： 5.567131519317627
2021-08-26 19:30:10,977    7720     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:30:11,155    7720     INFO test_运营用户创建审批.py(215) - 已完成修改WorldCheck的状态为FALSE
2021-08-26 19:30:15,188    7720     INFO test_运营用户创建审批.py(228) - 接口请求url为：
2021-08-26 19:30:15,189    7720     INFO test_运营用户创建审批.py(230) - 提交审核获取到的手机号为：11170251838
2021-08-26 19:30:15,256    7720     INFO test_运营用户创建审批.py(233) - 请求数据库cd_clnt_apply_info查询到applyId的值为：()
2021-08-26 19:30:15,289    7720     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-26 19:30:15,290    7720  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 246, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != 'JSON invalid format'
- 操作成功
+ JSON invalid format


2021-08-26 19:30:15,290    7720     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-26 19:30:15,290    7720     INFO result.py(91) - 耗时： 4.312788009643555
2021-08-26 19:30:15,290    6160     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:30:15,290    6160    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-26 19:30:15,291    6160     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:10.103935
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-27 08:50:02,847   10500     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 08:50:02,850   14800     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 08:50:02,880   14800     INFO test_运营用户创建审批.py(32) - 初始化 Session
2021-08-27 08:50:03,051   14800     INFO test_运营用户创建审批.py(42) - 接口请求url为：
2021-08-27 08:50:08,382   14800     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-27 08:50:08,382   14800     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 08:50:08,398   14800     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 08:50:08,398   14800     INFO result.py(91) - 耗时： 5.548180341720581
2021-08-27 08:50:08,414   14800     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 08:50:08,596   14800     INFO test_运营用户创建审批.py(215) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 08:50:12,689   14800     INFO test_运营用户创建审批.py(228) - 接口请求url为：
2021-08-27 08:50:12,690   14800     INFO test_运营用户创建审批.py(230) - 提交审核获取到的手机号为：12513509113
2021-08-27 08:50:12,767   14800     INFO test_运营用户创建审批.py(233) - 请求数据库cd_clnt_apply_info查询到applyId的值为：()
2021-08-27 08:50:12,792   14800     INFO test_运营用户创建审批.py(25) - 关闭 Session
2021-08-27 08:50:12,814   14800  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 246, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != 'JSON invalid format'
- 操作成功
+ JSON invalid format


2021-08-27 08:50:12,814   14800     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 08:50:12,814   14800     INFO result.py(91) - 耗时： 4.399883270263672
2021-08-27 08:50:12,814   10500     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 08:50:12,814   10500    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 08:50:12,815   10500     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:10.181411
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-27 09:11:32,489    5280     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 09:11:32,491   11820     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:11:32,748   11820     INFO test_运营用户创建审批.py(26) - 获取到的token为
2021-08-27 09:11:32,748   11820     INFO test_运营用户创建审批.py(33) - 初始化 Session
2021-08-27 09:11:32,779   11820     INFO test_运营用户创建审批.py(43) - 接口请求url为：
2021-08-27 09:11:38,121   11820     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:11:38,121   11820     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:11:38,137   11820     INFO result.py(91) - 耗时： 5.629961013793945
2021-08-27 09:11:38,137   11820     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:11:38,163   11820     INFO test_运营用户创建审批.py(26) - 获取到的token为
2021-08-27 09:11:38,300   11820     INFO test_运营用户创建审批.py(216) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 09:11:42,304   11820     INFO test_运营用户创建审批.py(229) - 接口请求url为：
2021-08-27 09:11:42,304   11820     INFO test_运营用户创建审批.py(231) - 提交审核获取到的手机号为：19149946102
2021-08-27 09:11:42,413   11820     INFO test_运营用户创建审批.py(234) - 请求数据库cd_clnt_apply_info查询到applyId的值为：()
2021-08-27 09:11:42,440   11820  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 247, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != 'JSON invalid format'
- 操作成功
+ JSON invalid format


2021-08-27 09:11:42,440   11820     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:11:42,440   11820     INFO result.py(91) - 耗时： 4.3020713329315186
2021-08-27 09:11:42,441    5280     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 09:11:42,441    5280    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 09:11:42,442    5280     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:10.149811
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-27 09:17:43,931    7664     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 09:17:43,933   27224     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:17:44,087   27224     INFO test_运营用户创建审批.py(28) - 获取到的token为
2021-08-27 09:17:44,119   27224     INFO test_运营用户创建审批.py(35) - 初始化 Session
2021-08-27 09:17:44,167   27224     INFO test_运营用户创建审批.py(45) - 接口请求url为：http://sit-cdms.ynm3k.com/api/client/applyClient
2021-08-27 09:17:49,560   27224     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:17:49,560   27224     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:17:49,575   27224     INFO result.py(91) - 耗时： 5.626944541931152
2021-08-27 09:17:49,575   27224     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:17:49,611   27224     INFO test_运营用户创建审批.py(28) - 获取到的token为
2021-08-27 09:17:49,750   27224     INFO test_运营用户创建审批.py(218) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 09:17:53,762   27224     INFO test_运营用户创建审批.py(231) - 接口请求url为：http://sit-cdms.ynm3k.com/api/client/submitAudit
2021-08-27 09:17:53,762   27224     INFO test_运营用户创建审批.py(233) - 提交审核获取到的手机号为：16352683968
2021-08-27 09:17:53,870   27224     INFO test_运营用户创建审批.py(236) - 请求数据库cd_clnt_apply_info查询到applyId的值为：()
2021-08-27 09:17:53,945   27224  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 249, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != 'JSON invalid format'
- 操作成功
+ JSON invalid format


2021-08-27 09:17:53,945   27224     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:17:53,945   27224     INFO result.py(91) - 耗时： 4.369535207748413
2021-08-27 09:17:53,945    7664     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 09:17:53,945    7664    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 09:17:53,946    7664     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:10.215198
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-27 09:20:20,380   18668     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 09:20:20,381   26588     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:20:20,381   26588    ERROR result.py(175) - 测试产生错误： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
TypeError: setUp() missing 1 required positional argument: 'cls'

2021-08-27 09:20:20,392   26588     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:20:20,408   26588     INFO result.py(91) - 耗时： 0.011001825332641602
2021-08-27 09:20:20,424   26588     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:20:20,424   26588    ERROR result.py(175) - 测试产生错误： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
TypeError: setUp() missing 1 required positional argument: 'cls'

2021-08-27 09:20:20,424   26588     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:20:20,424   26588     INFO result.py(91) - 耗时： 0.0
2021-08-27 09:20:20,424   18668    ERROR test_runner.py(195) - 
Error	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
Error	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 09:20:20,425   18668     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:00.251704
共计执行用例数量：2
执行成功用例数量：0
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：2

2021-08-27 09:22:10,392   10476     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 09:22:10,393   10708     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:22:10,653   10708     INFO test_运营用户创建审批.py(28) - 获取到的token为
2021-08-27 09:22:10,763   10708    ERROR result.py(175) - 测试产生错误： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 31, in test_applyClient用户资料提交
    eddidhost=self.eddidhost
AttributeError: 'Test_新建用户' object has no attribute 'eddidhost'

2021-08-27 09:22:10,779   10708    ERROR result.py(175) - 测试产生错误： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 252, in tearDown
    self.s.close()
AttributeError: 'Test_新建用户' object has no attribute 's'

2021-08-27 09:22:10,795   10708     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:22:10,811   10708     INFO result.py(91) - 耗时： 0.40195584297180176
2021-08-27 09:22:10,826   10708     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:22:10,846   10708     INFO test_运营用户创建审批.py(28) - 获取到的token为
2021-08-27 09:22:10,846   10708    ERROR result.py(175) - 测试产生错误： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 213, in test_submitAudit提交审核
    s = self.s
AttributeError: 'Test_新建用户' object has no attribute 's'

2021-08-27 09:22:10,847   10708    ERROR result.py(175) - 测试产生错误： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 252, in tearDown
    self.s.close()
AttributeError: 'Test_新建用户' object has no attribute 's'

2021-08-27 09:22:10,847   10708     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:22:10,847   10708     INFO result.py(91) - 耗时： 0.021164655685424805
2021-08-27 09:22:10,847   10476    ERROR test_runner.py(195) - 
Error	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
Error	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
Error	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Error	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 09:22:10,848   10476     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:00.649011
共计执行用例数量：2
执行成功用例数量：0
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：2

2021-08-27 09:27:04,907   10936     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 09:27:04,908   14700     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:27:04,908   14700     INFO test_运营用户创建审批.py(33) - 获取到的token为
2021-08-27 09:27:05,010   14700    ERROR result.py(175) - 测试产生错误： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 36, in test_applyClient用户资料提交
    eddidhost=self.eddidhost
AttributeError: 'Test_新建用户' object has no attribute 'eddidhost'

2021-08-27 09:27:05,040   14700     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:27:05,070   14700     INFO result.py(91) - 耗时： 0.13164997100830078
2021-08-27 09:27:05,070   14700     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:27:05,071   14700     INFO test_运营用户创建审批.py(33) - 获取到的token为
2021-08-27 09:27:05,071   14700    ERROR result.py(175) - 测试产生错误： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 220, in test_submitAudit提交审核
    eddidhost=self.eddidhost
AttributeError: 'Test_新建用户' object has no attribute 'eddidhost'

2021-08-27 09:27:05,071   14700     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 09:27:05,072   14700     INFO result.py(91) - 耗时： 0.0009965896606445312
2021-08-27 09:27:05,072   10936    ERROR test_runner.py(195) - 
Error	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
Error	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 09:27:05,073   10936     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:00.377346
共计执行用例数量：2
执行成功用例数量：0
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：2

2021-08-27 10:14:52,867   14660     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 10:14:52,868   27824     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:14:53,068   27824     INFO test_运营用户创建审批.py(33) - 获取到的token为
2021-08-27 10:14:53,132   27824    ERROR result.py(175) - 测试产生错误： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 36, in test_applyClient用户资料提交
    eddidhost=self.eddidhost
AttributeError: 'Test_新建用户' object has no attribute 'eddidhost'

2021-08-27 10:14:53,132   27824     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:14:53,148   27824     INFO result.py(91) - 耗时： 0.2643258571624756
2021-08-27 10:14:53,148   27824     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:14:53,167   27824     INFO test_运营用户创建审批.py(33) - 获取到的token为
2021-08-27 10:14:53,168   27824    ERROR result.py(175) - 测试产生错误： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 220, in test_submitAudit提交审核
    eddidhost=self.eddidhost
AttributeError: 'Test_新建用户' object has no attribute 'eddidhost'

2021-08-27 10:14:53,168   27824     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:14:53,168   27824     INFO result.py(91) - 耗时： 0.020041704177856445
2021-08-27 10:14:53,168   14660    ERROR test_runner.py(195) - 
Error	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
Error	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 10:14:53,169   14660     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:00.501839
共计执行用例数量：2
执行成功用例数量：0
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：2

2021-08-27 10:16:13,580   21456     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 10:16:13,580   11836     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:16:13,673   11836     INFO test_运营用户创建审批.py(33) - 获取到的token为
2021-08-27 10:16:13,780   11836    ERROR result.py(175) - 测试产生错误： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 37, in test_applyClient用户资料提交
    idCardNo=self.idCardNo
AttributeError: 'Test_新建用户' object has no attribute 'idCardNo'

2021-08-27 10:16:13,796   11836     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:16:13,828   11836     INFO result.py(91) - 耗时： 0.21445131301879883
2021-08-27 10:16:13,843   11836     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:16:13,864   11836     INFO test_运营用户创建审批.py(33) - 获取到的token为
2021-08-27 10:16:14,006   11836     INFO test_运营用户创建审批.py(223) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 10:16:18,019   11836     INFO test_运营用户创建审批.py(236) - 接口请求url为：http://sit-cdms.ynm3k.com/api/client/submitAudit
2021-08-27 10:16:18,019   11836     INFO test_运营用户创建审批.py(238) - 提交审核获取到的手机号为：19928165057
2021-08-27 10:16:18,102   11836     INFO test_运营用户创建审批.py(241) - 请求数据库cd_clnt_apply_info查询到applyId的值为：()
2021-08-27 10:16:18,153   11836  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 254, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != 'JSON invalid format'
- 操作成功
+ JSON invalid format


2021-08-27 10:16:18,154   11836     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:16:18,154   11836     INFO result.py(91) - 耗时： 4.311550140380859
2021-08-27 10:16:18,154   21456    ERROR test_runner.py(195) - 
Error	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 10:16:18,155   21456     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:04.777433
共计执行用例数量：2
执行成功用例数量：0
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：1

2021-08-27 10:16:51,563   25912     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 10:16:51,565    5452     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:16:51,667    5452     INFO test_运营用户创建审批.py(33) - 获取到的token为
2021-08-27 10:16:51,682    5452     INFO test_运营用户创建审批.py(40) - 初始化 Session
2021-08-27 10:16:51,714    5452     INFO test_运营用户创建审批.py(50) - 接口请求url为：http://sit-cdms.ynm3k.com/api/client/applyClient
2021-08-27 10:16:57,044    5452     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:16:57,044    5452     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:16:57,060    5452     INFO result.py(91) - 耗时： 5.479364395141602
2021-08-27 10:16:57,060    5452     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:16:57,083    5452     INFO test_运营用户创建审批.py(33) - 获取到的token为
2021-08-27 10:16:57,220    5452     INFO test_运营用户创建审批.py(223) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 10:17:01,233    5452     INFO test_运营用户创建审批.py(236) - 接口请求url为：http://sit-cdms.ynm3k.com/api/client/submitAudit
2021-08-27 10:17:01,233    5452     INFO test_运营用户创建审批.py(238) - 提交审核获取到的手机号为：19854642493
2021-08-27 10:17:01,311    5452     INFO test_运营用户创建审批.py(241) - 请求数据库cd_clnt_apply_info查询到applyId的值为：()
2021-08-27 10:17:01,373    5452  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 254, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != 'JSON invalid format'
- 操作成功
+ JSON invalid format


2021-08-27 10:17:01,373    5452     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:17:01,373    5452     INFO result.py(91) - 耗时： 4.3127899169921875
2021-08-27 10:17:01,373   25912     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 10:17:01,373   25912    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 10:17:01,374   25912     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:10.020235
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-27 10:46:03,305   17448     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 10:46:03,307   20528     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:46:03,542   20528    ERROR result.py(175) - 测试产生错误： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 26, in setUp
    print("身份证号", idCardNo)
NameError: name 'idCardNo' is not defined

2021-08-27 10:46:03,542   20528     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:46:03,557   20528     INFO result.py(91) - 耗时： 0.23536896705627441
2021-08-27 10:46:03,557   20528     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:46:03,577   20528    ERROR result.py(175) - 测试产生错误： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 26, in setUp
    print("身份证号", idCardNo)
NameError: name 'idCardNo' is not defined

2021-08-27 10:46:03,577   20528     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:46:03,577   20528     INFO result.py(91) - 耗时： 0.019841670989990234
2021-08-27 10:46:03,577   17448    ERROR test_runner.py(195) - 
Error	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
Error	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 10:46:03,579   17448     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:00.474730
共计执行用例数量：2
执行成功用例数量：0
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：2

2021-08-27 10:53:44,918   19848     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 10:53:44,920   23860     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:53:45,175   23860     INFO test_运营用户创建审批.py(27) - 获取到的token为
2021-08-27 10:53:45,313   23860    ERROR result.py(175) - 测试产生错误： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 31, in test_applyClient用户资料提交
    idCardNo=self.idCardNo
AttributeError: 'Test_新建用户' object has no attribute 'idCardNo'

2021-08-27 10:53:45,313   23860     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:53:45,313   23860     INFO result.py(91) - 耗时： 0.3929769992828369
2021-08-27 10:53:45,313   23860     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:53:45,333   23860     INFO test_运营用户创建审批.py(27) - 获取到的token为
2021-08-27 10:53:45,334   23860    ERROR result.py(175) - 测试产生错误： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 213, in test_submitAudit提交审核
    phone=self.phone
AttributeError: 'Test_新建用户' object has no attribute 'phone'

2021-08-27 10:53:45,334   23860     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:53:45,334   23860     INFO result.py(91) - 耗时： 0.021107196807861328
2021-08-27 10:53:45,334   19848    ERROR test_runner.py(195) - 
Error	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
Error	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 10:53:45,335   19848     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:00.624909
共计执行用例数量：2
执行成功用例数量：0
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：2

2021-08-27 10:55:26,386   25144     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 10:55:26,388    9372     INFO result.py(69) - 开始测试： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:55:26,610    9372     INFO test_运营用户创建审批.py(27) - 获取到的token为
2021-08-27 10:55:26,641    9372     INFO test_运营用户创建审批.py(34) - 初始化 Session
2021-08-27 10:55:26,753    9372     INFO test_运营用户创建审批.py(44) - 接口请求url为：http://sit-cdms.ynm3k.com/api/client/applyClient
2021-08-27 10:55:32,028    9372     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:55:32,028    9372     INFO result.py(90) - 测试结束： test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:55:32,028    9372     INFO result.py(91) - 耗时： 5.639939308166504
2021-08-27 10:55:32,044    9372     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:55:32,095    9372     INFO test_运营用户创建审批.py(27) - 获取到的token为
2021-08-27 10:55:32,278    9372     INFO test_运营用户创建审批.py(217) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 10:55:36,291    9372     INFO test_运营用户创建审批.py(230) - 接口请求url为：http://sit-cdms.ynm3k.com/api/client/submitAudit
2021-08-27 10:55:36,291    9372     INFO test_运营用户创建审批.py(232) - 提交审核获取到的手机号为：12862199894
2021-08-27 10:55:36,375    9372     INFO test_运营用户创建审批.py(235) - 请求数据库cd_clnt_apply_info查询到applyId的值为：()
2021-08-27 10:55:36,453    9372  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 248, in test_submitAudit提交审核
    self.assertEqual("操作成功", r.json().get("msg"))
AssertionError: '操作成功' != 'JSON invalid format'
- 操作成功
+ JSON invalid format


2021-08-27 10:55:36,453    9372     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 10:55:36,453    9372     INFO result.py(91) - 耗时： 4.409123420715332
2021-08-27 10:55:36,453   25144     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 10:55:36,453   25144    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 10:55:36,454   25144     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:10.267956
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-27 14:20:50,307   26288     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 14:20:50,308   24284     INFO result.py(69) - 开始测试： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:20:50,309   24284     INFO test_运营用户创建审批12.py(22) - 初始化CreatUser
2021-08-27 14:20:50,467   24284     INFO applyClient用户资料提交.py(29) - 接口请求url为：http://sit-cdms.ynm3k.com/api/client/applyClient
2021-08-27 14:20:50,701   24284     INFO test_运营用户创建审批12.py(28) - 资料提交接口'/api/client/applyClient'的响应结果为:'<Response [200]>'
2021-08-27 14:20:50,794   24284    ERROR result.py(175) - 测试产生错误： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批12.py", line 42, in tearDown
    self.s.close()
AttributeError: 'Test_新建用户' object has no attribute 's'

2021-08-27 14:20:50,794   24284     INFO result.py(90) - 测试结束： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:20:50,809   24284     INFO result.py(91) - 耗时： 0.4847538471221924
2021-08-27 14:20:50,840   24284     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:20:50,840   24284     INFO test_运营用户创建审批12.py(22) - 初始化CreatUser
2021-08-27 14:20:51,342   24284     INFO applyClient用户资料提交.py(195) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 14:20:55,353   24284     INFO applyClient用户资料提交.py(208) - 接口请求url为：http://sit-cdms.ynm3k.com/api/client/submitAudit
2021-08-27 14:20:55,353   24284     INFO applyClient用户资料提交.py(210) - 提交审核获取到的手机号为：12897117758
2021-08-27 14:20:55,905   24284     INFO test_运营用户创建审批12.py(37) - 资料提交接口'/api/client/submitAudit'的响应结果为:'<Response [200]>'
2021-08-27 14:20:55,907   24284  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批12.py", line 39, in test_submitAudit提交审核
    self.assertEqual("操作成功", submitAudit.json().get("msg"))
AssertionError: '操作成功' != '用户没有创建worldCheck或未关联，请检查，稍后操作'
- 操作成功
+ 用户没有创建worldCheck或未关联，请检查，稍后操作


2021-08-27 14:20:55,907   24284    ERROR result.py(175) - 测试产生错误： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批12.py", line 42, in tearDown
    self.s.close()
AttributeError: 'Test_新建用户' object has no attribute 's'

2021-08-27 14:20:55,907   24284     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:20:55,907   24284     INFO result.py(91) - 耗时： 5.067530393600464
2021-08-27 14:20:55,908   26288    ERROR test_runner.py(195) - 
Error	test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
Error	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)

2021-08-27 14:20:55,908   26288     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:05.801498
共计执行用例数量：3
执行成功用例数量：0
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：2

2021-08-27 14:21:48,347   18544     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 14:21:48,349    9220     INFO result.py(69) - 开始测试： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:21:48,349    9220     INFO test_运营用户创建审批12.py(21) - 初始化CreatUser
2021-08-27 14:21:48,614    9220     INFO applyClient用户资料提交.py(29) - 接口请求url为：http://sit-cdms.ynm3k.com/api/client/applyClient
2021-08-27 14:21:48,816    9220     INFO test_运营用户创建审批12.py(27) - 资料提交接口'/api/client/applyClient'的响应结果为:'<Response [200]>'
2021-08-27 14:21:48,816    9220     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:21:48,832    9220     INFO result.py(90) - 测试结束： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:21:48,832    9220     INFO result.py(91) - 耗时： 0.48326992988586426
2021-08-27 14:21:48,847    9220     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:21:48,847    9220     INFO test_运营用户创建审批12.py(21) - 初始化CreatUser
2021-08-27 14:21:49,316    9220     INFO applyClient用户资料提交.py(195) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 14:21:53,330    9220     INFO applyClient用户资料提交.py(208) - 接口请求url为：http://sit-cdms.ynm3k.com/api/client/submitAudit
2021-08-27 14:21:53,330    9220     INFO applyClient用户资料提交.py(210) - 提交审核获取到的手机号为：16761377312
2021-08-27 14:21:53,532    9220     INFO test_运营用户创建审批12.py(35) - 资料提交接口'/api/client/submitAudit'的响应结果为:'<Response [200]>'
2021-08-27 14:21:53,532    9220     INFO result.py(156) - 测试执行通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:21:53,532    9220     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:21:53,532    9220     INFO result.py(91) - 耗时： 4.684244394302368
2021-08-27 14:21:53,532   18544     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
Pass	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)

2021-08-27 14:21:53,533   18544     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:05.384644
共计执行用例数量：2
执行成功用例数量：2
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：0

2021-08-27 14:35:38,666   17240     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 14:35:38,668   17608     INFO result.py(69) - 开始测试： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:35:38,668   17608     INFO test_运营用户创建审批12.py(21) - 初始化CreatUser
2021-08-27 14:35:38,852   17608     INFO applyClient用户资料提交.py(19) - 获取到的token为
2021-08-27 14:35:38,868   17608     INFO applyClient用户资料提交.py(188) - 提交申请单时注册用户手机号码为：16692815525
2021-08-27 14:35:39,123   17608     INFO applyClient用户资料提交.py(190) - 接口'http://sit-cdms.ynm3k.com/api/client/applyClient'的响应结果为：'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 14:35:39,123   17608     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:35:39,139   17608     INFO result.py(90) - 测试结束： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:35:39,139   17608     INFO result.py(91) - 耗时： 0.47076845169067383
2021-08-27 14:35:39,139   17608     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:35:39,139   17608     INFO test_运营用户创建审批12.py(21) - 初始化CreatUser
2021-08-27 14:35:39,600   17608     INFO applyClient用户资料提交.py(195) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 14:35:43,605   17608     INFO applyClient用户资料提交.py(203) - 获取到的token为
2021-08-27 14:35:43,605   17608     INFO applyClient用户资料提交.py(211) - 提交审核获取到的手机号为：16692815525
2021-08-27 14:35:43,733   17608     INFO applyClient用户资料提交.py(223) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/submitAudit'的响应结果为:'{"code":"CDMS_04040","msg":"用户没有创建worldCheck或未关联，请检查，稍后操作","data":""}'
2021-08-27 14:35:43,733   17608  WARNING result.py(190) - 测试未通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批12.py", line 37, in test_submitAudit提交审核
    self.assertEqual("操作成功", submitAudit.json().get("msg"))
AssertionError: '操作成功' != '用户没有创建worldCheck或未关联，请检查，稍后操作'
- 操作成功
+ 用户没有创建worldCheck或未关联，请检查，稍后操作


2021-08-27 14:35:43,733   17608     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:35:43,733   17608     INFO result.py(91) - 耗时： 4.594277620315552
2021-08-27 14:35:43,733   17240     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)

2021-08-27 14:35:43,734   17240    ERROR test_runner.py(195) - 
Fail	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)

2021-08-27 14:35:43,735   17240     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:05.266241
共计执行用例数量：2
执行成功用例数量：1
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：0

2021-08-27 14:40:55,421   13568     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 14:40:55,422   18620     INFO result.py(69) - 开始测试： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:40:55,422   18620     INFO test_运营用户创建审批12.py(21) - 初始化CreatUser
2021-08-27 14:40:55,646   18620     INFO applyClient用户资料提交.py(19) - 获取到的token为
2021-08-27 14:40:55,693   18620     INFO applyClient用户资料提交.py(188) - 提交申请单时注册用户手机号码为：11492363009
2021-08-27 14:40:55,943   18620     INFO applyClient用户资料提交.py(190) - 接口'http://sit-cdms.ynm3k.com/api/client/applyClient'的响应结果为：'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 14:41:00,975   18620     INFO test_运营用户创建审批12.py(42) - 接口请求完成后，等待系统处理数据，等待5秒
2021-08-27 14:41:00,975   18620     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:41:00,990   18620     INFO result.py(90) - 测试结束： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:41:01,006   18620     INFO result.py(91) - 耗时： 5.5681304931640625
2021-08-27 14:41:01,022   18620     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:41:01,022   18620     INFO test_运营用户创建审批12.py(21) - 初始化CreatUser
2021-08-27 14:41:01,524   18620     INFO applyClient用户资料提交.py(195) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 14:41:05,527   18620     INFO applyClient用户资料提交.py(203) - 获取到的token为
2021-08-27 14:41:05,527   18620     INFO applyClient用户资料提交.py(211) - 提交审核获取到的手机号为：11492363009
2021-08-27 14:41:05,763   18620     INFO applyClient用户资料提交.py(223) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/submitAudit'的响应结果为:'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 14:41:10,773   18620     INFO test_运营用户创建审批12.py(42) - 接口请求完成后，等待系统处理数据，等待5秒
2021-08-27 14:41:10,773   18620     INFO result.py(156) - 测试执行通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:41:10,773   18620     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:41:10,773   18620     INFO result.py(91) - 耗时： 9.751163244247437
2021-08-27 14:41:10,773   13568     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
Pass	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)

2021-08-27 14:41:10,774   13568     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:15.572131
共计执行用例数量：2
执行成功用例数量：2
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：0

2021-08-27 14:42:41,294   25728     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 14:42:41,296   14344     INFO result.py(69) - 开始测试： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:42:41,296   14344     INFO test_运营用户创建审批12.py(21) - 初始化CreatUser
2021-08-27 14:42:41,427   14344     INFO applyClient用户资料提交.py(19) - 获取到的token为:DFBE3D9E2326647F4AEDD5B9E14CBD2E7AC79FFD18F78973
2021-08-27 14:42:41,473   14344     INFO applyClient用户资料提交.py(188) - 提交申请单时注册用户手机号码为：16760036201
2021-08-27 14:42:41,775   14344     INFO applyClient用户资料提交.py(190) - 接口'http://sit-cdms.ynm3k.com/api/client/applyClient'的响应结果为：'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 14:42:46,798   14344     INFO test_运营用户创建审批12.py(42) - 接口请求完成后，等待系统处理数据，等待5秒
2021-08-27 14:42:46,814   14344     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:42:46,814   14344     INFO result.py(90) - 测试结束： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:42:46,814   14344     INFO result.py(91) - 耗时： 5.518261909484863
2021-08-27 14:42:46,814   14344     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:42:46,814   14344     INFO test_运营用户创建审批12.py(21) - 初始化CreatUser
2021-08-27 14:42:47,291   14344     INFO applyClient用户资料提交.py(195) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 14:42:51,306   14344     INFO applyClient用户资料提交.py(203) - 获取到的token为:DFBE3D9E2326647F4AEDD5B9E14CBD2E7AC79FFD18F78973
2021-08-27 14:42:51,306   14344     INFO applyClient用户资料提交.py(211) - 提交审核获取到的手机号为：16760036201
2021-08-27 14:42:51,582   14344     INFO applyClient用户资料提交.py(223) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/submitAudit'的响应结果为:'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 14:42:56,599   14344     INFO test_运营用户创建审批12.py(42) - 接口请求完成后，等待系统处理数据，等待5秒
2021-08-27 14:42:56,599   14344     INFO result.py(156) - 测试执行通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:42:56,599   14344     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)
2021-08-27 14:42:56,599   14344     INFO result.py(91) - 耗时： 9.784134864807129
2021-08-27 14:42:56,599   25728     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批12.Test_新建用户)
Pass	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批12.Test_新建用户)

2021-08-27 14:42:56,600   25728     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:15.507141
共计执行用例数量：2
执行成功用例数量：2
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：0

2021-08-27 14:45:05,688   17656     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 14:45:05,689   11468     INFO result.py(69) - 开始测试： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 14:45:05,689   11468     INFO test_运营用户创建审批.py(21) - 初始化CreatUser
2021-08-27 14:45:05,830   11468     INFO applyClient用户资料提交.py(19) - 获取到的token为:DFBE3D9E2326647F7F40642834F444AE7AC79FFD18F78973
2021-08-27 14:45:05,830   11468     INFO applyClient用户资料提交.py(188) - 提交申请单时注册用户手机号码为：10305770198
2021-08-27 14:45:06,084   11468     INFO applyClient用户资料提交.py(190) - 接口'http://sit-cdms.ynm3k.com/api/client/applyClient'的响应结果为：'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 14:45:10,112   11468     INFO test_运营用户创建审批.py(42) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 14:45:10,112   11468     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 14:45:10,128   11468     INFO result.py(90) - 测试结束： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 14:45:10,143   11468     INFO result.py(91) - 耗时： 4.438156366348267
2021-08-27 14:45:10,158   11468     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 14:45:10,158   11468     INFO test_运营用户创建审批.py(21) - 初始化CreatUser
2021-08-27 14:45:10,615   11468     INFO applyClient用户资料提交.py(195) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 14:45:14,618   11468     INFO applyClient用户资料提交.py(203) - 获取到的token为:DFBE3D9E2326647F7F40642834F444AE7AC79FFD18F78973
2021-08-27 14:45:14,618   11468     INFO applyClient用户资料提交.py(211) - 提交审核获取到的手机号为：10305770198
2021-08-27 14:45:14,781   11468     INFO applyClient用户资料提交.py(223) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/submitAudit'的响应结果为:'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 14:45:18,794   11468     INFO test_运营用户创建审批.py(42) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 14:45:18,794   11468     INFO result.py(156) - 测试执行通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 14:45:18,794   11468     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 14:45:18,794   11468     INFO result.py(91) - 耗时： 8.635523080825806
2021-08-27 14:45:18,794   17656     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 14:45:18,795   17656     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:13.304824
共计执行用例数量：2
执行成功用例数量：2
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：0

2021-08-27 16:13:09,330    7100     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 16:13:09,332   15864     INFO result.py(69) - 开始测试： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:13:09,333   15864     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:13:09,613   15864     INFO CreatUser.py(25) - 当前token为:DFBE3D9E2326647FA2875FA2D4ED44B27AC79FFD18F78973
2021-08-27 16:13:09,613   15864     INFO CreatUser.py(189) - 提交申请单时注册用户手机号码为：11283317434
2021-08-27 16:13:09,970   15864     INFO CreatUser.py(191) - 接口'http://sit-cdms.ynm3k.com/api/client/applyClient'的响应结果为：'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 16:13:13,987   15864     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:13:13,987   15864     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:13:13,987   15864     INFO result.py(90) - 测试结束： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:13:14,003   15864     INFO result.py(91) - 耗时： 4.65357518196106
2021-08-27 16:13:14,019   15864     INFO result.py(69) - 开始测试： test_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:13:14,019   15864     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:13:14,019   15864     INFO CreatUser.py(229) - 当前token为:DFBE3D9E2326647FA2875FA2D4ED44B27AC79FFD18F78973
2021-08-27 16:13:14,019   15864     INFO CreatUser.py(237) - 提交审核获取到的手机号为：11283317434
2021-08-27 16:13:18,046   15864     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:13:18,156   15864    ERROR result.py(175) - 测试产生错误： test_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 36, in test_operatingWorkFlowFirst提交锁
    operatingWorkFlowFirst=self.creatUser.operatingWorkFlowFirst提交锁()
  File "F:\python\EDDID_CDMS\Business\CreatUser.py", line 240, in operatingWorkFlowFirst提交锁
    print("查询数据库cd_clnt_apply_info查询到applyId的值为：{}".format(applyId))
NameError: name 'applyId' is not defined

2021-08-27 16:13:18,172   15864     INFO result.py(90) - 测试结束： test_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:13:18,188   15864     INFO result.py(91) - 耗时： 4.1528918743133545
2021-08-27 16:13:18,188   15864     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:13:18,188   15864     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:13:18,653   15864     INFO CreatUser.py(196) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 16:13:18,653   15864     INFO CreatUser.py(204) - 当前token为:DFBE3D9E2326647FA2875FA2D4ED44B27AC79FFD18F78973
2021-08-27 16:13:18,653   15864     INFO CreatUser.py(209) - 提交审核获取到的手机号为：11283317434
2021-08-27 16:13:18,871   15864     INFO CreatUser.py(220) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/submitAudit'的响应结果为:'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 16:13:22,883   15864     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:13:22,883   15864     INFO result.py(156) - 测试执行通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:13:22,883   15864     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:13:22,883   15864     INFO result.py(91) - 耗时： 4.69536018371582
2021-08-27 16:13:22,884    7100     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 16:13:22,884    7100    ERROR test_runner.py(195) - 
Error	test_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 16:13:22,885    7100     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:13.758098
共计执行用例数量：3
执行成功用例数量：2
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：1

2021-08-27 16:18:09,171    9180     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 16:18:09,174   12348     INFO result.py(69) - 开始测试： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:18:09,180   12348     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:18:09,367   12348     INFO CreatUser.py(25) - 当前token为:DFBE3D9E2326647FAC4E9A9618AC73AB7AC79FFD18F78973
2021-08-27 16:18:09,415   12348     INFO CreatUser.py(189) - 提交申请单时注册用户手机号码为：10131829017
2021-08-27 16:18:09,667   12348     INFO CreatUser.py(191) - 接口'http://sit-cdms.ynm3k.com/api/client/applyClient'的响应结果为：'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 16:18:13,699   12348     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:18:13,699   12348     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:18:13,699   12348     INFO result.py(90) - 测试结束： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:18:13,715   12348     INFO result.py(91) - 耗时： 4.518905162811279
2021-08-27 16:18:13,731   12348     INFO result.py(69) - 开始测试： test_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:18:13,731   12348     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:18:13,731   12348     INFO CreatUser.py(229) - 当前token为:DFBE3D9E2326647FAC4E9A9618AC73AB7AC79FFD18F78973
2021-08-27 16:18:17,761   12348     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:18:17,869   12348    ERROR result.py(175) - 测试产生错误： test_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 36, in test_operatingWorkFlowFirst提交锁
    operatingWorkFlowFirst=self.creatUser.operatingWorkFlowFirst提交锁()
  File "F:\python\EDDID_CDMS\Business\CreatUser.py", line 240, in operatingWorkFlowFirst提交锁
    print("查询数据库cd_clnt_apply_info查询到applyId的值为：{}".format(applyId))
NameError: name 'applyId' is not defined

2021-08-27 16:18:17,869   12348     INFO result.py(90) - 测试结束： test_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:18:17,885   12348     INFO result.py(91) - 耗时： 4.137957811355591
2021-08-27 16:18:17,900   12348     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:18:17,900   12348     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:18:18,448   12348     INFO CreatUser.py(196) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 16:18:18,448   12348     INFO CreatUser.py(204) - 当前token为:DFBE3D9E2326647FAC4E9A9618AC73AB7AC79FFD18F78973
2021-08-27 16:18:18,448   12348     INFO CreatUser.py(209) - 提交审核获取到的手机号为：10131829017
2021-08-27 16:18:18,716   12348     INFO CreatUser.py(220) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/submitAudit'的响应结果为:'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 16:18:22,723   12348     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:18:22,723   12348     INFO result.py(156) - 测试执行通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:18:22,723   12348     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:18:22,723   12348     INFO result.py(91) - 耗时： 4.822773694992065
2021-08-27 16:18:22,723    9180     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 16:18:22,724    9180    ERROR test_runner.py(195) - 
Error	test_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 16:18:22,724    9180     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:13.765339
共计执行用例数量：3
执行成功用例数量：2
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：1

2021-08-27 16:19:01,440   17176     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 16:19:01,442   27632     INFO result.py(69) - 开始测试： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:19:01,442   27632     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:19:01,711   27632     INFO CreatUser.py(25) - 当前token为:DFBE3D9E2326647FE3AD50F22E98B8D67AC79FFD18F78973
2021-08-27 16:19:01,837   27632     INFO CreatUser.py(189) - 提交申请单时注册用户手机号码为：12161051364
2021-08-27 16:19:02,170   27632     INFO CreatUser.py(191) - 接口'http://sit-cdms.ynm3k.com/api/client/applyClient'的响应结果为：'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 16:19:06,219   27632     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:19:06,219   27632     INFO result.py(156) - 测试执行通过： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:19:06,235   27632     INFO result.py(90) - 测试结束： test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:19:06,235   27632     INFO result.py(91) - 耗时： 4.792201995849609
2021-08-27 16:19:06,251   27632     INFO result.py(69) - 开始测试： test_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:19:06,251   27632     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:19:06,251   27632     INFO CreatUser.py(229) - 当前token为:DFBE3D9E2326647FE3AD50F22E98B8D67AC79FFD18F78973
2021-08-27 16:19:06,969   27632     INFO CreatUser.py(248) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147691","applyNo":null,"result":false,"operatingMessage":"当前用户没有权限锁定/解锁该记录"}]}'
2021-08-27 16:19:10,997   27632     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:19:11,060   27632    ERROR result.py(175) - 测试产生错误： test_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 39, in test_operatingWorkFlowFirst提交锁
    self.assertEqual("操作成功", operatingWorkFlowFirst.json().get("data")[0].operatingMessage)
AttributeError: 'dict' object has no attribute 'operatingMessage'

2021-08-27 16:19:11,060   27632     INFO result.py(90) - 测试结束： test_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:19:11,076   27632     INFO result.py(91) - 耗时： 4.8098368644714355
2021-08-27 16:19:11,076   27632     INFO result.py(69) - 开始测试： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:19:11,076   27632     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:19:11,982   27632     INFO CreatUser.py(196) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 16:19:11,982   27632     INFO CreatUser.py(204) - 当前token为:DFBE3D9E2326647FE3AD50F22E98B8D67AC79FFD18F78973
2021-08-27 16:19:11,982   27632     INFO CreatUser.py(209) - 提交审核获取到的手机号为：12161051364
2021-08-27 16:19:12,267   27632     INFO CreatUser.py(220) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/submitAudit'的响应结果为:'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 16:19:16,280   27632     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:19:16,280   27632     INFO result.py(156) - 测试执行通过： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:19:16,280   27632     INFO result.py(90) - 测试结束： test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:19:16,280   27632     INFO result.py(91) - 耗时： 5.203612804412842
2021-08-27 16:19:16,281   17176     INFO test_runner.py(193) - 
Pass	test_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 16:19:16,281   17176    ERROR test_runner.py(195) - 
Error	test_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 16:19:16,282   17176     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:15.110892
共计执行用例数量：3
执行成功用例数量：2
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：1

2021-08-27 16:33:52,027   10988     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 16:33:52,029   14056     INFO result.py(69) - 开始测试： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:33:52,030   14056     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:33:52,223   14056     INFO CreatUser.py(25) - 当前token为:DFBE3D9E2326647F9F3AB68CC17926867AC79FFD18F78973
2021-08-27 16:33:52,238   14056     INFO CreatUser.py(189) - 提交申请单时注册用户手机号码为：11722114051
2021-08-27 16:33:52,460   14056     INFO CreatUser.py(191) - 接口'http://sit-cdms.ynm3k.com/api/client/applyClient'的响应结果为：'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 16:33:56,489   14056     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:33:56,489   14056     INFO result.py(156) - 测试执行通过： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:33:56,505   14056     INFO result.py(90) - 测试结束： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:33:56,505   14056     INFO result.py(91) - 耗时： 4.475052833557129
2021-08-27 16:33:56,505   14056     INFO result.py(69) - 开始测试： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:33:56,505   14056     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:33:57,095   14056     INFO CreatUser.py(196) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 16:33:57,095   14056     INFO CreatUser.py(204) - 当前token为:DFBE3D9E2326647F9F3AB68CC17926867AC79FFD18F78973
2021-08-27 16:33:57,142   14056     INFO CreatUser.py(209) - 提交审核获取到的手机号为：11722114051
2021-08-27 16:33:57,717   14056     INFO CreatUser.py(220) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/submitAudit'的响应结果为:'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 16:34:01,737   14056     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:34:01,753   14056     INFO result.py(156) - 测试执行通过： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:34:01,769   14056     INFO result.py(90) - 测试结束： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:34:01,769   14056     INFO result.py(91) - 耗时： 5.263883352279663
2021-08-27 16:34:01,785   14056     INFO result.py(69) - 开始测试： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:34:01,785   14056     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:34:01,785   14056     INFO CreatUser.py(229) - 当前token为:DFBE3D9E2326647F9F3AB68CC17926867AC79FFD18F78973
2021-08-27 16:34:01,893   14056     INFO CreatUser.py(248) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147692","applyNo":null,"result":true,"operatingMessage":"操作成功"}]}'
2021-08-27 16:34:05,899   14056     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:34:05,899   14056    ERROR result.py(175) - 测试产生错误： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 39, in test_3_operatingWorkFlowFirst提交锁
    self.assertEqual("操作成功", operatingWorkFlowFirst.json().get("data")[0].operatingMessage)
AttributeError: 'dict' object has no attribute 'operatingMessage'

2021-08-27 16:34:05,900   14056     INFO result.py(90) - 测试结束： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:34:05,900   14056     INFO result.py(91) - 耗时： 4.115649461746216
2021-08-27 16:34:05,900   10988     INFO test_runner.py(193) - 
Pass	test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 16:34:05,900   10988    ERROR test_runner.py(195) - 
Error	test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 16:34:05,901   10988     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:14.077272
共计执行用例数量：3
执行成功用例数量：2
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：1

2021-08-27 16:38:30,981     276     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 16:38:30,983   24532     INFO result.py(69) - 开始测试： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:38:30,983   24532     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:38:31,173   24532     INFO CreatUser.py(25) - 当前token为:DFBE3D9E2326647FD02B0497CFE4B76D7AC79FFD18F78973
2021-08-27 16:38:31,203   24532     INFO CreatUser.py(189) - 提交申请单时注册用户手机号码为：16166895271
2021-08-27 16:38:31,438   24532     INFO CreatUser.py(191) - 接口'http://sit-cdms.ynm3k.com/api/client/applyClient'的响应结果为：'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 16:38:35,454   24532     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:38:35,454   24532     INFO result.py(156) - 测试执行通过： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:38:35,454   24532     INFO result.py(90) - 测试结束： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:38:35,454   24532     INFO result.py(91) - 耗时： 4.470722913742065
2021-08-27 16:42:02,766   10336     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 16:42:02,768    9772     INFO result.py(69) - 开始测试： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:42:02,768    9772     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:42:02,992    9772     INFO CreatUser.py(25) - 当前token为:DFBE3D9E2326647FF724F94798671D947AC79FFD18F78973
2021-08-27 16:42:02,992    9772     INFO CreatUser.py(189) - 提交申请单时注册用户手机号码为：16322205537
2021-08-27 16:42:03,255    9772     INFO CreatUser.py(191) - 接口'http://sit-cdms.ynm3k.com/api/client/applyClient'的响应结果为：'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 16:42:07,282    9772     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:42:07,282    9772     INFO result.py(156) - 测试执行通过： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:42:07,298    9772     INFO result.py(90) - 测试结束： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:42:07,298    9772     INFO result.py(91) - 耗时： 4.529910326004028
2021-08-27 16:42:07,314    9772     INFO result.py(69) - 开始测试： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:42:07,314    9772     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:42:08,036    9772     INFO CreatUser.py(196) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 16:42:13,058    9772     INFO CreatUser.py(204) - 当前token为:DFBE3D9E2326647FF724F94798671D947AC79FFD18F78973
2021-08-27 16:42:13,073    9772     INFO CreatUser.py(209) - 提交审核获取到的手机号为：16322205537
2021-08-27 16:42:13,639    9772     INFO CreatUser.py(220) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/submitAudit'的响应结果为:'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 16:42:17,665    9772     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:42:17,665    9772     INFO result.py(156) - 测试执行通过： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:42:17,681    9772     INFO result.py(90) - 测试结束： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:42:17,697    9772     INFO result.py(91) - 耗时： 10.366955995559692
2021-08-27 16:42:17,697    9772     INFO result.py(69) - 开始测试： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:42:17,697    9772     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:42:17,697    9772     INFO CreatUser.py(229) - 当前token为:DFBE3D9E2326647FF724F94798671D947AC79FFD18F78973
2021-08-27 16:42:17,870    9772     INFO CreatUser.py(248) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147697","applyNo":null,"result":true,"operatingMessage":"操作成功"}]}'
2021-08-27 16:42:21,883    9772     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:42:21,884    9772    ERROR result.py(175) - 测试产生错误： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 39, in test_3_operatingWorkFlowFirst提交锁
    self.assertEqual("操作成功", operatingWorkFlowFirst.json().get("data")[0].operatingMessage)
AttributeError: 'dict' object has no attribute 'operatingMessage'

2021-08-27 16:42:21,884    9772     INFO result.py(90) - 测试结束： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:42:21,884    9772     INFO result.py(91) - 耗时： 4.187393426895142
2021-08-27 16:42:21,884   10336     INFO test_runner.py(193) - 
Pass	test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 16:42:21,884   10336    ERROR test_runner.py(195) - 
Error	test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 16:42:21,885   10336     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:19.315779
共计执行用例数量：3
执行成功用例数量：2
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：1

2021-08-27 16:43:33,806   23860     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 16:43:33,808   15188     INFO result.py(69) - 开始测试： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:43:33,808   15188     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:43:33,987   15188     INFO CreatUser.py(25) - 当前token为:DFBE3D9E2326647F5AF56AB6E792A7BB7AC79FFD18F78973
2021-08-27 16:43:34,115   15188     INFO CreatUser.py(189) - 提交申请单时注册用户手机号码为：16521663192
2021-08-27 16:43:34,366   15188     INFO CreatUser.py(191) - 接口'http://sit-cdms.ynm3k.com/api/client/applyClient'的响应结果为：'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 16:43:38,395   15188     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:43:38,395   15188     INFO result.py(156) - 测试执行通过： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:43:38,410   15188     INFO result.py(90) - 测试结束： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:43:38,442   15188     INFO result.py(91) - 耗时： 4.602489709854126
2021-08-27 16:43:38,458   15188     INFO result.py(69) - 开始测试： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:43:38,458   15188     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:43:39,323   15188     INFO CreatUser.py(196) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 16:43:44,343   15188     INFO CreatUser.py(204) - 当前token为:DFBE3D9E2326647F5AF56AB6E792A7BB7AC79FFD18F78973
2021-08-27 16:43:44,358   15188     INFO CreatUser.py(209) - 提交审核获取到的手机号为：16521663192
2021-08-27 16:43:44,765   15188     INFO CreatUser.py(220) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/submitAudit'的响应结果为:'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 16:43:48,795   15188     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:43:48,795   15188     INFO result.py(156) - 测试执行通过： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:43:48,795   15188     INFO result.py(90) - 测试结束： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:43:48,795   15188     INFO result.py(91) - 耗时： 10.337369680404663
2021-08-27 16:43:48,795   15188     INFO result.py(69) - 开始测试： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:43:48,795   15188     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 16:43:48,795   15188     INFO CreatUser.py(229) - 当前token为:DFBE3D9E2326647F5AF56AB6E792A7BB7AC79FFD18F78973
2021-08-27 16:43:48,951   15188     INFO CreatUser.py(248) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147698","applyNo":null,"result":true,"operatingMessage":"操作成功"}]}'
2021-08-27 16:43:52,962   15188     INFO test_运营用户创建审批.py(44) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 16:43:52,962   15188     INFO result.py(156) - 测试执行通过： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:43:52,962   15188     INFO result.py(90) - 测试结束： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 16:43:52,962   15188     INFO result.py(91) - 耗时： 4.1664557456970215
2021-08-27 16:43:52,962   23860     INFO test_runner.py(193) - 
Pass	test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 16:43:52,963   23860     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:19.359930
共计执行用例数量：3
执行成功用例数量：3
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：0

2021-08-27 19:58:32,530    6292     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 19:58:32,532   22996     INFO result.py(69) - 开始测试： test_10_batchOperatingWorkFlowEnd批量确认 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 19:58:32,541   22996     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 19:58:36,564   22996     INFO test_运营用户创建审批.py(86) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 19:58:36,752   22996    ERROR result.py(175) - 测试产生错误： test_10_batchOperatingWorkFlowEnd批量确认 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 74, in test_10_batchOperatingWorkFlowEnd批量确认
    batchOperatingWorkFlowEnd=self.creatUser.batchOperatingWorkFlowEnd批量确认()
  File "F:\python\EDDID_CDMS\Business\CreatUser.py", line 486, in batchOperatingWorkFlowEnd批量确认
    "Cookie": "LANGUAGE=zh_CN;GB-SYS-SID-SIT=" + token
NameError: name 'token' is not defined

2021-08-27 19:58:36,752   22996     INFO result.py(90) - 测试结束： test_10_batchOperatingWorkFlowEnd批量确认 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 19:58:36,768   22996     INFO result.py(91) - 耗时： 4.2107298374176025
2021-08-27 19:58:36,783   22996     INFO result.py(69) - 开始测试： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 19:58:36,783   22996     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 19:58:36,893   22996     INFO CreatUser.py(25) - 当前token为:DFBE3D9E2326647F88A0C438D1C227987AC79FFD18F78973
2021-08-27 19:58:36,893   22996     INFO CreatUser.py(189) - 提交申请单时注册用户手机号码为：19937132429
2021-08-27 19:58:37,283   22996     INFO CreatUser.py(191) - 接口'http://sit-cdms.ynm3k.com/api/client/applyClient'的响应结果为：'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 19:58:41,310   22996     INFO test_运营用户创建审批.py(86) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 19:58:41,310   22996     INFO result.py(156) - 测试执行通过： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 19:58:41,325   22996     INFO result.py(90) - 测试结束： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 19:58:41,325   22996     INFO result.py(91) - 耗时： 4.542212724685669
2021-08-27 19:58:41,325   22996     INFO result.py(69) - 开始测试： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 19:58:41,325   22996     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 19:58:42,049   22996     INFO CreatUser.py(196) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 19:58:47,060   22996     INFO CreatUser.py(204) - 当前token为:DFBE3D9E2326647F88A0C438D1C227987AC79FFD18F78973
2021-08-27 19:58:47,060   22996     INFO CreatUser.py(209) - 提交审核获取到的手机号为：19937132429
2021-08-27 19:58:47,364   22996     INFO CreatUser.py(220) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/submitAudit'的响应结果为:'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 19:58:51,375   22996     INFO test_运营用户创建审批.py(86) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 19:58:51,375   22996     INFO result.py(156) - 测试执行通过： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 19:58:51,375   22996     INFO result.py(90) - 测试结束： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 19:58:51,376   22996     INFO result.py(91) - 耗时： 10.049585103988647
2021-08-27 20:01:50,963   21720     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 20:01:50,965    9556     INFO result.py(69) - 开始测试： test_10_batchOperatingWorkFlowEnd批量确认 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:01:50,966    9556     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 20:01:55,013    9556     INFO test_运营用户创建审批.py(86) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:01:55,217    9556    ERROR result.py(175) - 测试产生错误： test_10_batchOperatingWorkFlowEnd批量确认 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 74, in test_10_batchOperatingWorkFlowEnd批量确认
    batchOperatingWorkFlowEnd=self.creatUser.batchOperatingWorkFlowEnd批量确认()
  File "F:\python\EDDID_CDMS\Business\CreatUser.py", line 486, in batchOperatingWorkFlowEnd批量确认
    "Cookie": "LANGUAGE=zh_CN;GB-SYS-SID-SIT=" + token
NameError: name 'token' is not defined

2021-08-27 20:01:55,232    9556     INFO result.py(90) - 测试结束： test_10_batchOperatingWorkFlowEnd批量确认 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:01:55,263    9556     INFO result.py(91) - 耗时： 4.266579866409302
2021-08-27 20:01:55,264    9556     INFO result.py(69) - 开始测试： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:01:55,264    9556     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 20:01:55,387    9556     INFO CreatUser.py(25) - 当前token为:DFBE3D9E2326647F7FF31D5501EC23137AC79FFD18F78973
2021-08-27 20:01:55,387    9556     INFO CreatUser.py(189) - 提交申请单时注册用户手机号码为：19471121168
2021-08-27 20:01:55,665    9556     INFO CreatUser.py(191) - 接口'http://sit-cdms.ynm3k.com/api/client/applyClient'的响应结果为：'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 20:01:59,686    9556     INFO test_运营用户创建审批.py(86) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:01:59,686    9556     INFO result.py(156) - 测试执行通过： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:01:59,702    9556     INFO result.py(90) - 测试结束： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:01:59,718    9556     INFO result.py(91) - 耗时： 4.438571214675903
2021-08-27 20:01:59,718    9556     INFO result.py(69) - 开始测试： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:01:59,718    9556     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 20:02:00,374    9556     INFO CreatUser.py(196) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 20:02:05,404    9556     INFO CreatUser.py(204) - 当前token为:DFBE3D9E2326647F7FF31D5501EC23137AC79FFD18F78973
2021-08-27 20:02:05,451    9556     INFO CreatUser.py(209) - 提交审核获取到的手机号为：19471121168
2021-08-27 20:02:05,986    9556     INFO CreatUser.py(220) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/submitAudit'的响应结果为:'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 20:02:10,016    9556     INFO test_运营用户创建审批.py(86) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:02:10,032    9556     INFO result.py(156) - 测试执行通过： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:10,032    9556     INFO result.py(90) - 测试结束： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:10,048    9556     INFO result.py(91) - 耗时： 10.313869953155518
2021-08-27 20:02:10,048    9556     INFO result.py(69) - 开始测试： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:10,048    9556     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 20:02:10,049    9556     INFO CreatUser.py(230) - 当前token为:DFBE3D9E2326647F7FF31D5501EC23137AC79FFD18F78973
2021-08-27 20:02:10,188    9556     INFO CreatUser.py(249) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147701","applyNo":null,"result":true,"operatingMessage":"操作成功"}]}'
2021-08-27 20:02:14,220    9556     INFO test_运营用户创建审批.py(86) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:02:14,236    9556     INFO result.py(156) - 测试执行通过： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:14,252    9556     INFO result.py(90) - 测试结束： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:14,252    9556     INFO result.py(91) - 耗时： 4.203778028488159
2021-08-27 20:02:14,252    9556     INFO result.py(69) - 开始测试： test_4_saveRiskAssessment风控评估提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:14,252    9556     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 20:02:14,252    9556     INFO CreatUser.py(258) - 当前token为:DFBE3D9E2326647F7FF31D5501EC23137AC79FFD18F78973
2021-08-27 20:02:14,391    9556     INFO CreatUser.py(287) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/saveRiskAssessment'的响应结果为:'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 20:02:18,423    9556     INFO test_运营用户创建审批.py(86) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:02:18,423    9556     INFO result.py(156) - 测试执行通过： test_4_saveRiskAssessment风控评估提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:18,423    9556     INFO result.py(90) - 测试结束： test_4_saveRiskAssessment风控评估提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:18,423    9556     INFO result.py(91) - 耗时： 4.171066999435425
2021-08-27 20:02:18,423    9556     INFO result.py(69) - 开始测试： test_5_operatingWorkFlow内部人员审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:18,424    9556     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 20:02:18,424    9556     INFO CreatUser.py(296) - 当前token为:DFBE3D9E2326647F7FF31D5501EC23137AC79FFD18F78973
2021-08-27 20:02:18,640    9556     INFO CreatUser.py(394) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147701","applyNo":null,"result":true,"operatingMessage":""}]}'
2021-08-27 20:02:22,662    9556     INFO test_运营用户创建审批.py(86) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:02:22,678    9556  WARNING result.py(190) - 测试未通过： test_5_operatingWorkFlow内部人员审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 48, in test_5_operatingWorkFlow内部人员审核
    self.assertEqual("true", operatingWorkFlow.json().get("data")[0].get("result"))
AssertionError: 'true' != True

2021-08-27 20:02:22,693    9556     INFO result.py(90) - 测试结束： test_5_operatingWorkFlow内部人员审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:22,725    9556     INFO result.py(91) - 耗时： 4.269601583480835
2021-08-27 20:02:22,725    9556     INFO result.py(69) - 开始测试： test_6_operatingWorkFlowNo不用锁定审核通过 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:22,726    9556     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 20:02:22,726    9556     INFO CreatUser.py(403) - 当前token为:DFBE3D9E2326647F7FF31D5501EC23137AC79FFD18F78973
2021-08-27 20:02:22,836    9556     INFO CreatUser.py(422) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147701","applyNo":null,"result":false,"operatingMessage":"当前用户没有权限锁定/解锁该记录"}]}'
2021-08-27 20:02:26,854    9556     INFO test_运营用户创建审批.py(86) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:02:26,870    9556  WARNING result.py(190) - 测试未通过： test_6_operatingWorkFlowNo不用锁定审核通过 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 54, in test_6_operatingWorkFlowNo不用锁定审核通过
    self.assertEqual("true", operatingWorkFlowNo.json().get("data")[0].get("result"))
AssertionError: 'true' != False

2021-08-27 20:02:26,870    9556     INFO result.py(90) - 测试结束： test_6_operatingWorkFlowNo不用锁定审核通过 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:26,870    9556     INFO result.py(91) - 耗时： 4.144911527633667
2021-08-27 20:02:26,871    9556     INFO result.py(69) - 开始测试： test_7_operatingWorkFlowAgaint提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:26,871    9556     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 20:02:26,871    9556     INFO CreatUser.py(431) - 当前token为:DFBE3D9E2326647F7FF31D5501EC23137AC79FFD18F78973
2021-08-27 20:02:26,933    9556     INFO CreatUser.py(450) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147701","applyNo":null,"result":false,"operatingMessage":"当前用户没有权限锁定/解锁该记录"}]}'
2021-08-27 20:02:30,964    9556     INFO test_运营用户创建审批.py(86) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:02:30,979    9556  WARNING result.py(190) - 测试未通过： test_7_operatingWorkFlowAgaint提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 60, in test_7_operatingWorkFlowAgaint提交锁
    self.assertEqual("操作成功", operatingWorkFlowAgaint.json().get("data")[0].get("operatingMessage"))
AssertionError: '操作成功' != '当前用户没有权限锁定/解锁该记录'
- 操作成功
+ 当前用户没有权限锁定/解锁该记录


2021-08-27 20:02:30,995    9556     INFO result.py(90) - 测试结束： test_7_operatingWorkFlowAgaint提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:30,995    9556     INFO result.py(91) - 耗时： 4.124555826187134
2021-08-27 20:02:30,995    9556     INFO result.py(69) - 开始测试： test_8_batchOperatingWorkFlow批量生成账号确定 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:30,995    9556     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 20:02:35,019    9556     INFO test_运营用户创建审批.py(86) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:02:35,050    9556    ERROR result.py(175) - 测试产生错误： test_8_batchOperatingWorkFlow批量生成账号确定 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 63, in test_8_batchOperatingWorkFlow批量生成账号确定
    batchOperatingWorkFlow=self.creatUser.batchOperatingWorkFlow批量生成账号确定()
AttributeError: 'CreatUser' object has no attribute 'batchOperatingWorkFlow批量生成账号确定'

2021-08-27 20:02:35,050    9556     INFO result.py(90) - 测试结束： test_8_batchOperatingWorkFlow批量生成账号确定 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:35,066    9556     INFO result.py(91) - 耗时： 4.054149627685547
2021-08-27 20:02:35,082    9556     INFO result.py(69) - 开始测试： test_9_operatingWorkFlowThird提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:35,082    9556     INFO test_运营用户创建审批.py(20) - 初始化CreatUser
2021-08-27 20:02:35,082    9556     INFO CreatUser.py(460) - 当前token为:DFBE3D9E2326647F7FF31D5501EC23137AC79FFD18F78973
2021-08-27 20:02:35,082    9556     INFO CreatUser.py(471) - applyId:1147701
2021-08-27 20:02:35,145    9556     INFO CreatUser.py(479) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147701","applyNo":null,"result":false,"operatingMessage":"当前用户没有权限锁定/解锁该记录"}]}'
2021-08-27 20:02:39,152    9556     INFO test_运营用户创建审批.py(86) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:02:39,152    9556  WARNING result.py(190) - 测试未通过： test_9_operatingWorkFlowThird提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 71, in test_9_operatingWorkFlowThird提交锁
    self.assertEqual("操作成功", operatingWorkFlowThird.json().get("data")[0].get("operatingMessage"))
AssertionError: '操作成功' != '当前用户没有权限锁定/解锁该记录'
- 操作成功
+ 当前用户没有权限锁定/解锁该记录


2021-08-27 20:02:39,152    9556     INFO result.py(90) - 测试结束： test_9_operatingWorkFlowThird提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:02:39,152    9556     INFO result.py(91) - 耗时： 4.070264577865601
2021-08-27 20:02:39,152   21720     INFO test_runner.py(193) - 
Pass	test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_4_saveRiskAssessment风控评估提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 20:02:39,152   21720    ERROR test_runner.py(195) - 
Error	test_10_batchOperatingWorkFlowEnd批量确认 (Test_Case.test_运营用户创建审批.Test_新建用户)
Fail	test_5_operatingWorkFlow内部人员审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Fail	test_6_operatingWorkFlowNo不用锁定审核通过 (Test_Case.test_运营用户创建审批.Test_新建用户)
Fail	test_7_operatingWorkFlowAgaint提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Error	test_8_batchOperatingWorkFlow批量生成账号确定 (Test_Case.test_运营用户创建审批.Test_新建用户)
Fail	test_9_operatingWorkFlowThird提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 20:02:39,153   21720     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:48.386908
共计执行用例数量：10
执行成功用例数量：4
执行失败用例数量：4
跳过执行用例数量：0
产生异常用例数量：2

2021-08-27 20:15:47,090    5620     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 20:15:47,094    9024     INFO result.py(69) - 开始测试： test_10_batchOperatingWorkFlowEnd批量确认 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:15:47,113    9024     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:15:51,132    9024     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:15:51,292    9024    ERROR result.py(175) - 测试产生错误： test_10_batchOperatingWorkFlowEnd批量确认 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 73, in test_10_batchOperatingWorkFlowEnd批量确认
    batchOperatingWorkFlowEnd = self.creatUser.batchOperatingWorkFlowEnd批量确认()
  File "F:\python\EDDID_CDMS\Business\CreatUser.py", line 529, in batchOperatingWorkFlowEnd批量确认
    "Cookie": "LANGUAGE=zh_CN;GB-SYS-SID-SIT=" + token
NameError: name 'token' is not defined

2021-08-27 20:15:51,292    9024     INFO result.py(90) - 测试结束： test_10_batchOperatingWorkFlowEnd批量确认 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:15:51,292    9024     INFO result.py(91) - 耗时： 4.178874969482422
2021-08-27 20:15:51,293    9024     INFO result.py(69) - 开始测试： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:15:51,293    9024     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:15:51,433    9024     INFO CreatUser.py(26) - 当前token为:DFBE3D9E2326647F242C3735A9D2B6267AC79FFD18F78973
2021-08-27 20:15:51,433    9024     INFO CreatUser.py(190) - 提交申请单时注册用户手机号码为：12220032030
2021-08-27 20:15:51,694    9024     INFO CreatUser.py(192) - 接口'http://sit-cdms.ynm3k.com/api/client/applyClient'的响应结果为：'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 20:15:55,713    9024     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:15:55,713    9024     INFO result.py(156) - 测试执行通过： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:15:55,713    9024     INFO result.py(90) - 测试结束： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:15:55,713    9024     INFO result.py(91) - 耗时： 4.419936418533325
2021-08-27 20:15:55,713    9024     INFO result.py(69) - 开始测试： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:15:55,713    9024     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:15:56,350    9024     INFO CreatUser.py(198) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 20:16:01,372    9024     INFO CreatUser.py(206) - 当前token为:DFBE3D9E2326647F242C3735A9D2B6267AC79FFD18F78973
2021-08-27 20:16:01,372    9024     INFO CreatUser.py(211) - 提交审核获取到的手机号为：12220032030
2021-08-27 20:16:02,010    9024     INFO CreatUser.py(222) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/submitAudit'的响应结果为:'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 20:16:06,040    9024     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:16:06,040    9024     INFO result.py(156) - 测试执行通过： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:06,040    9024     INFO result.py(90) - 测试结束： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:06,040    9024     INFO result.py(91) - 耗时： 10.327362060546875
2021-08-27 20:16:06,040    9024     INFO result.py(69) - 开始测试： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:06,041    9024     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:16:06,041    9024     INFO CreatUser.py(232) - 当前token为:DFBE3D9E2326647F242C3735A9D2B6267AC79FFD18F78973
2021-08-27 20:16:06,403    9024     INFO CreatUser.py(251) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147702","applyNo":null,"result":true,"operatingMessage":"操作成功"}]}'
2021-08-27 20:16:10,427    9024     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:16:10,427    9024     INFO result.py(156) - 测试执行通过： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:10,427    9024     INFO result.py(90) - 测试结束： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:10,427    9024     INFO result.py(91) - 耗时： 4.3867974281311035
2021-08-27 20:16:10,427    9024     INFO result.py(69) - 开始测试： test_4_saveRiskAssessment风控评估提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:10,427    9024     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:16:10,428    9024     INFO CreatUser.py(261) - 当前token为:DFBE3D9E2326647F242C3735A9D2B6267AC79FFD18F78973
2021-08-27 20:16:10,428    9024     INFO CreatUser.py(266) - 当前applyId为：1147702
2021-08-27 20:16:10,612    9024     INFO CreatUser.py(290) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/saveRiskAssessment'的响应结果为:'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 20:16:14,628    9024     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:16:14,628    9024     INFO result.py(156) - 测试执行通过： test_4_saveRiskAssessment风控评估提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:14,628    9024     INFO result.py(90) - 测试结束： test_4_saveRiskAssessment风控评估提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:14,628    9024     INFO result.py(91) - 耗时： 4.201754808425903
2021-08-27 20:16:14,628    9024     INFO result.py(69) - 开始测试： test_5_operatingWorkFlow内部人员审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:14,629    9024     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:16:14,644    9024     INFO CreatUser.py(300) - 当前token为:DFBE3D9E2326647F242C3735A9D2B6267AC79FFD18F78973
2021-08-27 20:16:14,864    9024     INFO CreatUser.py(398) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147702","applyNo":null,"result":true,"operatingMessage":""}]}'
2021-08-27 20:16:18,893    9024     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:16:18,909    9024  WARNING result.py(190) - 测试未通过： test_5_operatingWorkFlow内部人员审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 45, in test_5_operatingWorkFlow内部人员审核
    self.assertEqual("true", operatingWorkFlow.json().get("data")[0].get("result"))
AssertionError: 'true' != True

2021-08-27 20:16:18,925    9024     INFO result.py(90) - 测试结束： test_5_operatingWorkFlow内部人员审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:18,925    9024     INFO result.py(91) - 耗时： 4.2955310344696045
2021-08-27 20:16:18,925    9024     INFO result.py(69) - 开始测试： test_6_operatingWorkFlowNo不用锁定审核通过 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:18,925    9024     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:16:18,925    9024     INFO CreatUser.py(408) - 当前token为:DFBE3D9E2326647F242C3735A9D2B6267AC79FFD18F78973
2021-08-27 20:16:18,926    9024     INFO CreatUser.py(419) - 当前applyId为：1147702
2021-08-27 20:16:19,051    9024     INFO CreatUser.py(427) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147702","applyNo":null,"result":false,"operatingMessage":"当前用户没有权限锁定/解锁该记录"}]}'
2021-08-27 20:16:23,068    9024     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:16:23,083    9024  WARNING result.py(190) - 测试未通过： test_6_operatingWorkFlowNo不用锁定审核通过 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 51, in test_6_operatingWorkFlowNo不用锁定审核通过
    self.assertEqual("true", operatingWorkFlowNo.json().get("data")[0].get("result"))
AssertionError: 'true' != False

2021-08-27 20:16:23,083    9024     INFO result.py(90) - 测试结束： test_6_operatingWorkFlowNo不用锁定审核通过 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:23,083    9024     INFO result.py(91) - 耗时： 4.157872438430786
2021-08-27 20:16:23,083    9024     INFO result.py(69) - 开始测试： test_7_operatingWorkFlowAgaint提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:23,084    9024     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:16:23,084    9024     INFO CreatUser.py(437) - 当前token为:DFBE3D9E2326647F242C3735A9D2B6267AC79FFD18F78973
2021-08-27 20:16:23,160    9024     INFO CreatUser.py(456) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147702","applyNo":null,"result":false,"operatingMessage":"当前用户没有权限锁定/解锁该记录"}]}'
2021-08-27 20:16:27,179    9024     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:16:27,195    9024  WARNING result.py(190) - 测试未通过： test_7_operatingWorkFlowAgaint提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 57, in test_7_operatingWorkFlowAgaint提交锁
    self.assertEqual("操作成功", operatingWorkFlowAgaint.json().get("data")[0].get("operatingMessage"))
AssertionError: '操作成功' != '当前用户没有权限锁定/解锁该记录'
- 操作成功
+ 当前用户没有权限锁定/解锁该记录


2021-08-27 20:16:27,195    9024     INFO result.py(90) - 测试结束： test_7_operatingWorkFlowAgaint提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:27,195    9024     INFO result.py(91) - 耗时： 4.110996961593628
2021-08-27 20:16:27,195    9024     INFO result.py(69) - 开始测试： test_8_batchOperatingWorkFlow批量生成账号确定 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:27,195    9024     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:16:27,195    9024     INFO CreatUser.py(466) - 当前token为:DFBE3D9E2326647F242C3735A9D2B6267AC79FFD18F78973
2021-08-27 20:16:27,333    9024     INFO CreatUser.py(492) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/batchOperatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147702","applyNo":null,"result":false,"operatingMessage":"您当前没权限进行此操作"}]}'
2021-08-27 20:16:31,359    9024     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:16:31,375    9024  WARNING result.py(190) - 测试未通过： test_8_batchOperatingWorkFlow批量生成账号确定 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 63, in test_8_batchOperatingWorkFlow批量生成账号确定
    self.assertEqual("true", batchOperatingWorkFlow.json().get("data")[0].get("result"))
AssertionError: 'true' != False

2021-08-27 20:16:31,407    9024     INFO result.py(90) - 测试结束： test_8_batchOperatingWorkFlow批量生成账号确定 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:31,407    9024     INFO result.py(91) - 耗时： 4.211926221847534
2021-08-27 20:16:31,407    9024     INFO result.py(69) - 开始测试： test_9_operatingWorkFlowThird提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:31,407    9024     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:16:31,407    9024     INFO CreatUser.py(502) - 当前token为:DFBE3D9E2326647F242C3735A9D2B6267AC79FFD18F78973
2021-08-27 20:16:31,407    9024     INFO CreatUser.py(513) - 当前applyId为：1147702
2021-08-27 20:16:31,436    9024     INFO CreatUser.py(521) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147702","applyNo":null,"result":false,"operatingMessage":"当前用户没有权限锁定/解锁该记录"}]}'
2021-08-27 20:16:35,438    9024     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:16:35,438    9024  WARNING result.py(190) - 测试未通过： test_9_operatingWorkFlowThird提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 69, in test_9_operatingWorkFlowThird提交锁
    self.assertEqual("操作成功", operatingWorkFlowThird.json().get("data")[0].get("operatingMessage"))
AssertionError: '操作成功' != '当前用户没有权限锁定/解锁该记录'
- 操作成功
+ 当前用户没有权限锁定/解锁该记录


2021-08-27 20:16:35,438    9024     INFO result.py(90) - 测试结束： test_9_operatingWorkFlowThird提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:16:35,438    9024     INFO result.py(91) - 耗时： 4.0312769412994385
2021-08-27 20:16:35,439    5620     INFO test_runner.py(193) - 
Pass	test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_4_saveRiskAssessment风控评估提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 20:16:35,439    5620    ERROR test_runner.py(195) - 
Error	test_10_batchOperatingWorkFlowEnd批量确认 (Test_Case.test_运营用户创建审批.Test_新建用户)
Fail	test_5_operatingWorkFlow内部人员审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Fail	test_6_operatingWorkFlowNo不用锁定审核通过 (Test_Case.test_运营用户创建审批.Test_新建用户)
Fail	test_7_operatingWorkFlowAgaint提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Fail	test_8_batchOperatingWorkFlow批量生成账号确定 (Test_Case.test_运营用户创建审批.Test_新建用户)
Fail	test_9_operatingWorkFlowThird提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 20:16:35,440    5620     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:48.544648
共计执行用例数量：10
执行成功用例数量：4
执行失败用例数量：5
跳过执行用例数量：0
产生异常用例数量：1

2021-08-27 20:17:24,056   26996     INFO test_runner.py(156) - 预计并发线程数：1
2021-08-27 20:17:24,059   23032     INFO result.py(69) - 开始测试： test_10_batchOperatingWorkFlowEnd批量确认 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:24,059   23032     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:17:28,104   23032     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:17:28,275   23032    ERROR result.py(175) - 测试产生错误： test_10_batchOperatingWorkFlowEnd批量确认 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 73, in test_10_batchOperatingWorkFlowEnd批量确认
    batchOperatingWorkFlowEnd = self.creatUser.batchOperatingWorkFlowEnd批量确认()
  File "F:\python\EDDID_CDMS\Business\CreatUser.py", line 529, in batchOperatingWorkFlowEnd批量确认
    "Cookie": "LANGUAGE=zh_CN;GB-SYS-SID-SIT=" + token
NameError: name 'token' is not defined

2021-08-27 20:17:28,275   23032     INFO result.py(90) - 测试结束： test_10_batchOperatingWorkFlowEnd批量确认 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:28,291   23032     INFO result.py(91) - 耗时： 4.215716361999512
2021-08-27 20:17:28,291   23032     INFO result.py(69) - 开始测试： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:28,291   23032     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:17:28,415   23032     INFO CreatUser.py(26) - 当前token为:DFBE3D9E2326647FD63EC62A9A48B2877AC79FFD18F78973
2021-08-27 20:17:28,415   23032     INFO CreatUser.py(190) - 提交申请单时注册用户手机号码为：10334530415
2021-08-27 20:17:28,679   23032     INFO CreatUser.py(192) - 接口'http://sit-cdms.ynm3k.com/api/client/applyClient'的响应结果为：'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 20:17:32,713   23032     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:17:32,713   23032     INFO result.py(156) - 测试执行通过： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:32,729   23032     INFO result.py(90) - 测试结束： test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:32,729   23032     INFO result.py(91) - 耗时： 4.4381797313690186
2021-08-27 20:17:32,745   23032     INFO result.py(69) - 开始测试： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:32,745   23032     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:17:33,308   23032     INFO CreatUser.py(198) - 已完成修改WorldCheck的状态为FALSE
2021-08-27 20:17:38,327   23032     INFO CreatUser.py(206) - 当前token为:DFBE3D9E2326647FD63EC62A9A48B2877AC79FFD18F78973
2021-08-27 20:17:38,327   23032     INFO CreatUser.py(211) - 提交审核获取到的手机号为：10334530415
2021-08-27 20:17:38,793   23032     INFO CreatUser.py(222) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/submitAudit'的响应结果为:'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 20:17:42,821   23032     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:17:42,836   23032     INFO result.py(156) - 测试执行通过： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:42,836   23032     INFO result.py(90) - 测试结束： test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:42,852   23032     INFO result.py(91) - 耗时： 10.091378211975098
2021-08-27 20:17:42,852   23032     INFO result.py(69) - 开始测试： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:42,852   23032     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:17:42,852   23032     INFO CreatUser.py(232) - 当前token为:DFBE3D9E2326647FD63EC62A9A48B2877AC79FFD18F78973
2021-08-27 20:17:43,205   23032     INFO CreatUser.py(251) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147703","applyNo":null,"result":true,"operatingMessage":"操作成功"}]}'
2021-08-27 20:17:47,227   23032     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:17:47,243   23032     INFO result.py(156) - 测试执行通过： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:47,243   23032     INFO result.py(90) - 测试结束： test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:47,258   23032     INFO result.py(91) - 耗时： 4.39066481590271
2021-08-27 20:17:47,258   23032     INFO result.py(69) - 开始测试： test_4_saveRiskAssessment风控评估提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:47,258   23032     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:17:47,258   23032     INFO CreatUser.py(261) - 当前token为:DFBE3D9E2326647FD63EC62A9A48B2877AC79FFD18F78973
2021-08-27 20:17:47,259   23032     INFO CreatUser.py(266) - 当前applyId为：1147703
2021-08-27 20:17:47,412   23032     INFO CreatUser.py(290) - 提交审核接口'http://sit-cdms.ynm3k.com/api/client/saveRiskAssessment'的响应结果为:'{"code":"0000","msg":"操作成功","data":null}'
2021-08-27 20:17:51,443   23032     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:17:51,443   23032     INFO result.py(156) - 测试执行通过： test_4_saveRiskAssessment风控评估提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:51,459   23032     INFO result.py(90) - 测试结束： test_4_saveRiskAssessment风控评估提交 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:51,459   23032     INFO result.py(91) - 耗时： 4.200756788253784
2021-08-27 20:17:51,475   23032     INFO result.py(69) - 开始测试： test_5_operatingWorkFlow内部人员审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:51,475   23032     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:17:51,475   23032     INFO CreatUser.py(300) - 当前token为:DFBE3D9E2326647FD63EC62A9A48B2877AC79FFD18F78973
2021-08-27 20:17:51,679   23032     INFO CreatUser.py(398) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147703","applyNo":null,"result":true,"operatingMessage":""}]}'
2021-08-27 20:17:55,697   23032     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:17:55,713   23032  WARNING result.py(190) - 测试未通过： test_5_operatingWorkFlow内部人员审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 45, in test_5_operatingWorkFlow内部人员审核
    self.assertEqual("true", operatingWorkFlow.json().get("data")[0].get("result"))
AssertionError: 'true' != True

2021-08-27 20:17:55,729   23032     INFO result.py(90) - 测试结束： test_5_operatingWorkFlow内部人员审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:55,729   23032     INFO result.py(91) - 耗时： 4.254615545272827
2021-08-27 20:17:55,745   23032     INFO result.py(69) - 开始测试： test_6_operatingWorkFlowNo不用锁定审核通过 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:17:55,745   23032     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:17:55,745   23032     INFO CreatUser.py(408) - 当前token为:DFBE3D9E2326647FD63EC62A9A48B2877AC79FFD18F78973
2021-08-27 20:17:55,974   23032     INFO CreatUser.py(419) - 当前applyId为：1147703
2021-08-27 20:17:56,128   23032     INFO CreatUser.py(427) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147703","applyNo":null,"result":false,"operatingMessage":"当前用户没有权限锁定/解锁该记录"}]}'
2021-08-27 20:18:00,148   23032     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:18:00,164   23032  WARNING result.py(190) - 测试未通过： test_6_operatingWorkFlowNo不用锁定审核通过 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 51, in test_6_operatingWorkFlowNo不用锁定审核通过
    self.assertEqual("true", operatingWorkFlowNo.json().get("data")[0].get("result"))
AssertionError: 'true' != False

2021-08-27 20:18:00,164   23032     INFO result.py(90) - 测试结束： test_6_operatingWorkFlowNo不用锁定审核通过 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:18:00,164   23032     INFO result.py(91) - 耗时： 4.4191718101501465
2021-08-27 20:18:00,164   23032     INFO result.py(69) - 开始测试： test_7_operatingWorkFlowAgaint提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:18:00,164   23032     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:18:00,165   23032     INFO CreatUser.py(437) - 当前token为:DFBE3D9E2326647FD63EC62A9A48B2877AC79FFD18F78973
2021-08-27 20:18:00,722   23032     INFO CreatUser.py(456) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147703","applyNo":null,"result":false,"operatingMessage":"当前用户没有权限锁定/解锁该记录"}]}'
2021-08-27 20:18:04,741   23032     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:18:04,773   23032  WARNING result.py(190) - 测试未通过： test_7_operatingWorkFlowAgaint提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 57, in test_7_operatingWorkFlowAgaint提交锁
    self.assertEqual("操作成功", operatingWorkFlowAgaint.json().get("data")[0].get("operatingMessage"))
AssertionError: '操作成功' != '当前用户没有权限锁定/解锁该记录'
- 操作成功
+ 当前用户没有权限锁定/解锁该记录


2021-08-27 20:18:04,773   23032     INFO result.py(90) - 测试结束： test_7_operatingWorkFlowAgaint提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:18:04,773   23032     INFO result.py(91) - 耗时： 4.608753442764282
2021-08-27 20:18:04,774   23032     INFO result.py(69) - 开始测试： test_8_batchOperatingWorkFlow批量生成账号确定 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:18:04,774   23032     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:18:04,774   23032     INFO CreatUser.py(466) - 当前token为:DFBE3D9E2326647FD63EC62A9A48B2877AC79FFD18F78973
2021-08-27 20:18:05,349   23032     INFO CreatUser.py(492) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/batchOperatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147703","applyNo":null,"result":false,"operatingMessage":"您当前没权限进行此操作"}]}'
2021-08-27 20:18:09,379   23032     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:18:09,379   23032  WARNING result.py(190) - 测试未通过： test_8_batchOperatingWorkFlow批量生成账号确定 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 63, in test_8_batchOperatingWorkFlow批量生成账号确定
    self.assertEqual("true", batchOperatingWorkFlow.json().get("data")[0].get("result"))
AssertionError: 'true' != False

2021-08-27 20:18:09,379   23032     INFO result.py(90) - 测试结束： test_8_batchOperatingWorkFlow批量生成账号确定 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:18:09,379   23032     INFO result.py(91) - 耗时： 4.604742050170898
2021-08-27 20:18:09,379   23032     INFO result.py(69) - 开始测试： test_9_operatingWorkFlowThird提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:18:09,380   23032     INFO test_运营用户创建审批.py(17) - 初始化CreatUser
2021-08-27 20:18:09,380   23032     INFO CreatUser.py(502) - 当前token为:DFBE3D9E2326647FD63EC62A9A48B2877AC79FFD18F78973
2021-08-27 20:18:09,457   23032     INFO CreatUser.py(513) - 当前applyId为：1147703
2021-08-27 20:18:09,487   23032     INFO CreatUser.py(521) - 提交审核接口'http://sit-cdms.ynm3k.com/api/common/operatingWorkFlow'的响应结果为:'{"code":"0000","msg":"操作成功","data":[{"applyId":"1147703","applyNo":null,"result":false,"operatingMessage":"当前用户没有权限锁定/解锁该记录"}]}'
2021-08-27 20:18:13,494   23032     INFO test_运营用户创建审批.py(82) - 接口请求完成后，等待系统处理数据，等待4秒
2021-08-27 20:18:13,494   23032  WARNING result.py(190) - 测试未通过： test_9_operatingWorkFlowThird提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Traceback (most recent call last):
  File "F:\python\EDDID_CDMS\Test_Case\test_运营用户创建审批.py", line 69, in test_9_operatingWorkFlowThird提交锁
    self.assertEqual("操作成功", operatingWorkFlowThird.json().get("data")[0].get("operatingMessage"))
AssertionError: '操作成功' != '当前用户没有权限锁定/解锁该记录'
- 操作成功
+ 当前用户没有权限锁定/解锁该记录


2021-08-27 20:18:13,494   23032     INFO result.py(90) - 测试结束： test_9_operatingWorkFlowThird提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
2021-08-27 20:18:13,495   23032     INFO result.py(91) - 耗时： 4.114508390426636
2021-08-27 20:18:13,495   26996     INFO test_runner.py(193) - 
Pass	test_1_applyClient用户资料提交用例校验 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_2_submitAudit提交审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_3_operatingWorkFlowFirst提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Pass	test_4_saveRiskAssessment风控评估提交 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 20:18:13,495   26996    ERROR test_runner.py(195) - 
Error	test_10_batchOperatingWorkFlowEnd批量确认 (Test_Case.test_运营用户创建审批.Test_新建用户)
Fail	test_5_operatingWorkFlow内部人员审核 (Test_Case.test_运营用户创建审批.Test_新建用户)
Fail	test_6_operatingWorkFlowNo不用锁定审核通过 (Test_Case.test_运营用户创建审批.Test_新建用户)
Fail	test_7_operatingWorkFlowAgaint提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)
Fail	test_8_batchOperatingWorkFlow批量生成账号确定 (Test_Case.test_运营用户创建审批.Test_新建用户)
Fail	test_9_operatingWorkFlowThird提交锁 (Test_Case.test_运营用户创建审批.Test_新建用户)

2021-08-27 20:18:13,496   26996     INFO test_runner.py(213) - 
测试结束！
运行时间: 0:00:49.638713
共计执行用例数量：10
执行成功用例数量：4
执行失败用例数量：5
跳过执行用例数量：0
产生异常用例数量：1

